Repository kubernetes/kubernetes, pull requests merged in 2018-02, with the labels that each got.

#59607 Pass pvc namespace and annotations to Portworx Create API
  pkg/volume/portworx/portworx_util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59232 Make log content more information
  pkg/volume/glusterfs/glusterfs.go
  pkg/volume/glusterfs/glusterfs_util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59481 devicemanager: increase code coverege of endpoint's unit test
  pkg/kubelet/cm/devicemanager/endpoint_test.go
Labels: approved, area/hw-accelerators, cncf-cla: yes, lgtm, release-note-none, size/S

#59447 Fixes the regression of GCEPD not provisioning correctly on GKE alpha clusters.
  pkg/cloudprovider/providers/gce/gce_disks.go
  pkg/volume/gce_pd/BUILD
  pkg/volume/gce_pd/attacher.go
  pkg/volume/gce_pd/attacher_test.go
  pkg/volume/gce_pd/gce_util.go
Labels: approved, cherrypick-candidate, cncf-cla: yes, kind/bug, lgtm, milestone/needs-approval, priority/important-soon, release-note-none, sig/storage, size/L

#59594 Workaround patch using cached version in TestPatch
  staging/src/k8s.io/apiextensions-apiserver/test/integration/basic_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59651 Print stderr from go tool pprof in profile gatherer
  test/e2e/framework/profile_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59389 Fix typo: constucts -> constructs
  staging/src/k8s.io/metrics/pkg/client/custom_metrics/client.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59382 Disallow PriorityClass names with 'system-' prefix for user defined priority classes
  pkg/apis/scheduling/types.go
  pkg/apis/scheduling/validation/validation.go
  pkg/apis/scheduling/validation/validation_test.go
  plugin/pkg/admission/priority/admission.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note, sig/scheduling, size/S

#59424 Update etcd version from 3.1.10 to 3.2.14 when upgrading a K8s cluster to use IP aliases on GCP.
  cluster/gce/upgrade-aliases.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59672 GCE: Bump GLBC version to 0.9.8-alpha.1
  cluster/gce/manifests/glbc.manifest
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59313 [e2e gce-ingress] Scale test to measure ingress create/update latency
  test/e2e/framework/ingress_utils.go
  test/e2e/network/BUILD
  test/e2e/network/ingress.go
  test/e2e/network/ingress_scale.go
  test/e2e/network/scale/BUILD
  test/e2e/network/scale/ingress.go
  test/e2e/network/scale/localrun/BUILD
  test/e2e/network/scale/localrun/ingress_scale.go
  test/e2e/upgrades/ingress.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#59661 Disable symbol resolution by pprof in profile-gatherer
  test/e2e/framework/profile_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scalability, size/S

#59514 vSphere test infrastructure improvement and new node-unregister test
  test/e2e/storage/vsphere/BUILD
  test/e2e/storage/vsphere/bootstrap.go
  test/e2e/storage/vsphere/bootstrap/BUILD
  test/e2e/storage/vsphere/config.go
  test/e2e/storage/vsphere/connection.go
  test/e2e/storage/vsphere/context.go
  test/e2e/storage/vsphere/nodemapper.go
  test/e2e/storage/vsphere/vsphere.go
  test/e2e/storage/vsphere/vsphere_utils.go
  test/e2e/storage/vsphere/vsphere_volume_cluster_ds.go
  test/e2e/storage/vsphere/vsphere_volume_datastore.go
  test/e2e/storage/vsphere/vsphere_volume_diskformat.go
  test/e2e/storage/vsphere/vsphere_volume_disksize.go
  test/e2e/storage/vsphere/vsphere_volume_fstype.go
  test/e2e/storage/vsphere/vsphere_volume_master_restart.go
  test/e2e/storage/vsphere/vsphere_volume_node_delete.go
  test/e2e/storage/vsphere/vsphere_volume_node_poweroff.go
  test/e2e/storage/vsphere/vsphere_volume_ops_storm.go
  test/e2e/storage/vsphere/vsphere_volume_perf.go
  test/e2e/storage/vsphere/vsphere_volume_placement.go
  test/e2e/storage/vsphere/vsphere_volume_vsan_policy.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#59604 Automated cherry pick of #59539: Set instanceID to azure resource ID format while
  pkg/cloudprovider/providers/azure/azure_instances.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, size/XS

#58399 Update Kubeadm proxy handling for IPv6
  cmd/kubeadm/app/preflight/checks.go
  cmd/kubeadm/app/preflight/checks_test.go
Labels: approved, area/ipv6, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, sig/network, size/L

#59540 return error if New-SmbGlobalMapping failed when mounting azure file on Windows
  pkg/util/mount/mount_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/windows, size/XS

#59678 juju: Fix Services unreachable when externalTrafficPolicy=Local on AWS
  cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59130 Update Calico to version v2.6.7
  cluster/addons/calico-policy-controller/calico-node-daemonset.yaml
  cluster/addons/calico-policy-controller/typha-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS

#59655 Check etcd port instead of process name
  hack/lib/etcd.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#51339 add more error logs in kubectl run
  pkg/kubectl/cmd/run.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/cli, size/S

#59628 Bury KubeletConfiguration.ConfigTrialDuration for now
  pkg/kubelet/apis/kubeletconfig/helpers_test.go
  pkg/kubelet/apis/kubeletconfig/types.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/defaults.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/types.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.conversion.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/kubelet/apis/kubeletconfig/zz_generated.deepcopy.go
  pkg/kubelet/kubeletconfig/controller.go
  test/e2e_node/dynamic_kubelet_config_test.go
Labels: approved, area/kubelet, area/kubelet-api, cncf-cla: yes, lgtm, release-note, sig/node, size/M

#59520 Add generic cache for Azure VM/LB/NSG/RouteTable
  pkg/cloudprovider/providers/azure/azure.go
  pkg/cloudprovider/providers/azure/azure_backoff.go
  pkg/cloudprovider/providers/azure/azure_cache.go
  pkg/cloudprovider/providers/azure/azure_cache_test.go
  pkg/cloudprovider/providers/azure/azure_controllerCommon.go
  pkg/cloudprovider/providers/azure/azure_loadbalancer.go
  pkg/cloudprovider/providers/azure/azure_routes.go
  pkg/cloudprovider/providers/azure/azure_routes_test.go
  pkg/cloudprovider/providers/azure/azure_test.go
  pkg/cloudprovider/providers/azure/azure_wrap.go
Labels: approved, cncf-cla: yes, kind/enhancement, lgtm, release-note, size/XL

#59234 Adding kubemci e2e test for ingress spec conformance
  test/e2e/framework/ingress_utils.go
  test/e2e/framework/util.go
  test/e2e/manifest/BUILD
  test/e2e/manifest/manifest.go
  test/e2e/manifest/manifest_test.go
  test/e2e/network/ingress.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#58364 [kube-proxy]fix bad error message in kube-proxy.log when run cluster in local
  pkg/proxy/ipvs/netlink_linux.go
  pkg/util/ipset/ipset.go
Labels: approved, area/ipvs, area/kube-proxy, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/network, size/S

#59715 New github id - FengyunPan -> FengyunPan2
  pkg/cloudprovider/providers/openstack/OWNERS
  pkg/volume/cinder/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#56557 fix the create azure file pvc failure if there is no storage account in current resource group
  pkg/cloudprovider/providers/azure/BUILD
  pkg/cloudprovider/providers/azure/azure_blobDiskController.go
  pkg/cloudprovider/providers/azure/azure_standard.go
  pkg/cloudprovider/providers/azure/azure_standard_test.go
  pkg/cloudprovider/providers/azure/azure_storage.go
  pkg/cloudprovider/providers/azure/azure_storageaccount.go
  pkg/volume/azure_file/azure_provision.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, sig/azure, size/L

#58960 kubeadm: imagePullPolicy option in init config
  cmd/kubeadm/app/apis/kubeadm/BUILD
  cmd/kubeadm/app/apis/kubeadm/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/BUILD
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
  cmd/kubeadm/app/cmd/init.go
  cmd/kubeadm/app/phases/controlplane/manifests.go
  cmd/kubeadm/app/phases/etcd/local.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/M

#58737 Subtract local ephemeral storage resource from NodeInfo when removing pod
  pkg/scheduler/schedulercache/cache_test.go
  pkg/scheduler/schedulercache/node_info.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/scheduling, sig/storage, size/M

#59652 Add generic cache for Azure VMSS
  pkg/cloudprovider/providers/azure/BUILD
  pkg/cloudprovider/providers/azure/azure.go
  pkg/cloudprovider/providers/azure/azure_fakes.go
  pkg/cloudprovider/providers/azure/azure_vmss.go
  pkg/cloudprovider/providers/azure/azure_vmss_cache.go
  pkg/cloudprovider/providers/azure/azure_vmss_cache_test.go
  pkg/cloudprovider/providers/azure/azure_vmss_test.go
Labels: approved, cncf-cla: yes, kind/enhancement, lgtm, release-note, sig/azure, size/XL

#59506 fix --watch on multiple requests
  hack/make-rules/test-cmd-util.sh
  pkg/kubectl/cmd/resource/get.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59747 Map correct vmset name for internal load balancers
  pkg/cloudprovider/providers/azure/azure_standard.go
  pkg/cloudprovider/providers/azure/azure_standard_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, sig/azure, size/M

#59640 correct the ConstructVolumeSpec func path value
  pkg/volume/cephfs/cephfs.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59067 Feature Gate - Kubeadm Audit Logging
  cmd/kubeadm/app/apis/kubeadm/fuzzer/fuzzer.go
  cmd/kubeadm/app/apis/kubeadm/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/defaults.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.deepcopy.go
  cmd/kubeadm/app/apis/kubeadm/zz_generated.deepcopy.go
  cmd/kubeadm/app/cmd/BUILD
  cmd/kubeadm/app/cmd/init.go
  cmd/kubeadm/app/cmd/upgrade/common_test.go
  cmd/kubeadm/app/constants/constants.go
  cmd/kubeadm/app/features/features.go
  cmd/kubeadm/app/phases/controlplane/BUILD
  cmd/kubeadm/app/phases/controlplane/manifests.go
  cmd/kubeadm/app/phases/controlplane/manifests_test.go
  cmd/kubeadm/app/phases/controlplane/volumes.go
  cmd/kubeadm/app/phases/controlplane/volumes_test.go
  cmd/kubeadm/app/util/BUILD
  cmd/kubeadm/app/util/audit/BUILD
  cmd/kubeadm/app/util/audit/utils.go
  cmd/kubeadm/app/util/audit/utils_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/auth, sig/cluster-lifecycle, size/L

#59571 Skip TestRoutes when there are no vm(s)
  pkg/cloudprovider/providers/openstack/openstack_routes_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59291 Remove validation failure of Pod priority when the feature is disabled
  pkg/apis/core/validation/validation.go
  pkg/apis/core/validation/validation_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/scheduling, size/M

#59359 Remove controller-manager --service-sync-period flag
  cmd/cloud-controller-manager/app/options/options_test.go
  cmd/controller-manager/app/options/utils.go
  cmd/kube-controller-manager/app/options/options.go
  cmd/kube-controller-manager/app/options/options_test.go
  pkg/apis/componentconfig/types.go
  pkg/apis/componentconfig/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, priority/important-soon, release-note, sig/api-machinery, size/XS

#59767 kubelet: check for illegal phase transition
  pkg/kubelet/kubelet_pods.go
Labels: approved, cherrypick-candidate, cncf-cla: yes, kind/bug, lgtm, milestone/needs-approval, priority/important-soon, release-note-none, sig/node, size/XS

#56454 Block Volume: Refactor volumehandler in operationexecutor
  pkg/kubelet/volumemanager/reconciler/reconciler.go
  pkg/kubelet/volumemanager/reconciler/reconciler_test.go
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_executor_test.go
  pkg/volume/util/operationexecutor/operation_generator.go
  pkg/volume/util/volumehelper/BUILD
  pkg/volume/util/volumehelper/volumehelper.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/XL

#59237 Change critical pods’ template to use priority
  cluster/addons/calico-policy-controller/calico-node-daemonset.yaml
  cluster/addons/calico-policy-controller/calico-node-vertical-autoscaler-deployment.yaml
  cluster/addons/calico-policy-controller/typha-deployment.yaml
  cluster/addons/calico-policy-controller/typha-horizontal-autoscaler-deployment.yaml
  cluster/addons/calico-policy-controller/typha-vertical-autoscaler-deployment.yaml
  cluster/addons/cluster-monitoring/google/heapster-controller.yaml
  cluster/addons/cluster-monitoring/googleinfluxdb/heapster-controller-combined.yaml
  cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml
  cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml
  cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
  cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml
  cluster/addons/dashboard/dashboard-controller.yaml
  cluster/addons/dns-horizontal-autoscaler/dns-horizontal-autoscaler.yaml
  cluster/addons/dns/kube-dns.yaml.base
  cluster/addons/dns/kube-dns.yaml.in
  cluster/addons/dns/kube-dns.yaml.sed
  cluster/addons/etcd-empty-dir-cleanup/etcd-empty-dir-cleanup.yaml
  cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
  cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml
  cluster/addons/ip-masq-agent/ip-masq-agent.yaml
  cluster/addons/metadata-proxy/gce/metadata-proxy.yaml
  cluster/addons/metrics-server/metrics-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59730 Requesting new credentials when node names change
  cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#55479 kubeadm: add configuration option to not taint master
  cmd/kubeadm/app/apis/kubeadm/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
  cmd/kubeadm/app/cmd/init.go
  cmd/kubeadm/app/cmd/phases/markmaster.go
  cmd/kubeadm/app/phases/markmaster/markmaster.go
  cmd/kubeadm/app/phases/markmaster/markmaster_test.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/M

#59479 Avoid race condition when updating equivalence cache
  pkg/scheduler/core/equivalence_cache.go
  pkg/scheduler/core/equivalence_cache_test.go
  pkg/scheduler/core/generic_scheduler.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59246 Add tests for schedulercache
  pkg/scheduler/schedulercache/BUILD
  pkg/scheduler/schedulercache/node_info_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scheduling, size/XL

#59298 Add etcd 3.x minor version rollback support to migrate-if-needed.sh
  cluster/gce/manifests/etcd.manifest
  cluster/images/etcd/Dockerfile
  cluster/images/etcd/Makefile
  cluster/images/etcd/README.md
  cluster/images/etcd/migrate-if-needed.sh
  cluster/images/etcd/start-stop-etcd.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#59773 Bump GLBC to 0.9.8-alpha.2 and change back to --verbose
  cluster/gce/manifests/glbc.manifest
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59772 bazel: update digests for debian-iptables-amd64 and busybox
  build/root/WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59739 fix the error prone account creation method of blob disk
  pkg/cloudprovider/providers/azure/azure_blobDiskController.go
  pkg/cloudprovider/providers/azure/azure_storage.go
  pkg/cloudprovider/providers/azure/azure_storageaccount.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, sig/azure, size/L

#57969 Add gnufied as AWS approver.
  pkg/cloudprovider/providers/aws/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, sig/aws, size/XS

#59645 remove unused function printIndentedJson and printAllPods in test/integration/scheduler
  test/integration/scheduler/local-pv-neg-affinity_test.go
  test/integration/scheduler/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#52528 Refactor kube-proxy service/endpoints update so that can be consumed among different proxiers
  pkg/proxy/BUILD
  pkg/proxy/endpoints.go
  pkg/proxy/endpoints_test.go
  pkg/proxy/iptables/BUILD
  pkg/proxy/iptables/proxier.go
  pkg/proxy/iptables/proxier_test.go
  pkg/proxy/ipvs/BUILD
  pkg/proxy/ipvs/proxier.go
  pkg/proxy/ipvs/proxier_test.go
  pkg/proxy/service.go
  pkg/proxy/service_test.go
  pkg/proxy/types.go
  pkg/proxy/util/endpoints.go
Labels: approved, area/kube-proxy, cncf-cla: yes, lgtm, release-note, sig/network, size/XXL

#59671 Improve performance of scheduling queue by adding a hash map to track all pods with a nominatedNodeName
  pkg/scheduler/core/scheduling_queue.go
  pkg/scheduler/core/scheduling_queue_test.go
  pkg/scheduler/factory/factory.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scheduling, size/L

#57656 code-generator: add boilerplate header
  hack/update-codegen.sh
  hack/update-generated-protobuf-dockerized.sh
  staging/BUILD
  staging/src/k8s.io/code-generator/cmd/client-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/client-gen/main.go
  staging/src/k8s.io/code-generator/cmd/conversion-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/conversion-gen/main.go
  staging/src/k8s.io/code-generator/cmd/deepcopy-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go
  staging/src/k8s.io/code-generator/cmd/defaulter-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/defaulter-gen/main.go
  staging/src/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/BUILD
  staging/src/k8s.io/code-generator/cmd/go-to-protobuf/protobuf/cmd.go
  staging/src/k8s.io/code-generator/cmd/import-boss/BUILD
  staging/src/k8s.io/code-generator/cmd/import-boss/main.go
  staging/src/k8s.io/code-generator/cmd/informer-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/informer-gen/main.go
  staging/src/k8s.io/code-generator/cmd/lister-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/lister-gen/main.go
  staging/src/k8s.io/code-generator/cmd/openapi-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/openapi-gen/main.go
  staging/src/k8s.io/code-generator/cmd/set-gen/BUILD
  staging/src/k8s.io/code-generator/cmd/set-gen/main.go
  staging/src/k8s.io/code-generator/hack/BUILD
  staging/src/k8s.io/code-generator/hack/boilerplate.go.txt
  staging/src/k8s.io/code-generator/pkg/util/build.go
Labels: approved, area/code-generation, cncf-cla: yes, lgtm, release-note-none, size/M

#53766 Remove /ui/ redirect
  cmd/kube-apiserver/app/server.go
  hack/make-rules/test-cmd-util.sh
  pkg/master/master.go
  pkg/routes/BUILD
  pkg/routes/ui.go
  test/e2e/ui/dashboard.go
  test/integration/openshift/openshift_test.go
Labels: approved, area/apiserver, cncf-cla: yes, lgtm, release-note, sig/api-machinery, sig/ui, size/M

#59795 Increase timeout on waiting on cluster resize in autoscaling tests
  test/e2e/autoscaling/cluster_size_autoscaling.go
Labels: approved, area/test, cncf-cla: yes, lgtm, release-note-none, retest-not-required, size/XS

#55306 Audit support resource wildcard matching
  staging/src/k8s.io/apiserver/pkg/apis/audit/types.go
  staging/src/k8s.io/apiserver/pkg/apis/audit/v1alpha1/generated.proto
  staging/src/k8s.io/apiserver/pkg/apis/audit/v1alpha1/types.go
  staging/src/k8s.io/apiserver/pkg/apis/audit/v1beta1/generated.proto
  staging/src/k8s.io/apiserver/pkg/apis/audit/v1beta1/types.go
  staging/src/k8s.io/apiserver/pkg/audit/policy/checker.go
  staging/src/k8s.io/apiserver/pkg/audit/policy/checker_test.go
Labels: approved, area/audit, cncf-cla: yes, lgtm, release-note, sig/auth, size/M

#58937 pass listener in integration test
  staging/src/k8s.io/apiserver/pkg/server/options/serving.go
  staging/src/k8s.io/kube-aggregator/main.go
  staging/src/k8s.io/kube-aggregator/pkg/cmd/server/start.go
  staging/src/k8s.io/sample-apiserver/main.go
  staging/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go
  test/integration/etcd/BUILD
  test/integration/etcd/etcd_storage_path_test.go
  test/integration/examples/BUILD
  test/integration/examples/apiserver_test.go
  test/integration/framework/master_utils.go
  test/integration/tls/BUILD
  test/integration/tls/ciphers_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#59779 Remove myself (timothysc) from OWNERS files on areas that I do not maintain
  pkg/api/v1/OWNERS
  pkg/apis/OWNERS
  pkg/apis/apps/OWNERS
  pkg/apis/authentication/OWNERS
  pkg/apis/authorization/OWNERS
  pkg/apis/autoscaling/OWNERS
  pkg/apis/batch/OWNERS
  pkg/apis/certificates/OWNERS
  pkg/apis/componentconfig/OWNERS
  pkg/apis/core/OWNERS
  pkg/apis/core/v1/OWNERS
  pkg/apis/extensions/OWNERS
  pkg/apis/rbac/OWNERS
  staging/src/k8s.io/api/OWNERS
  staging/src/k8s.io/api/apps/OWNERS
  staging/src/k8s.io/api/authentication/OWNERS
  staging/src/k8s.io/api/authorization/OWNERS
  staging/src/k8s.io/api/autoscaling/OWNERS
  staging/src/k8s.io/api/batch/OWNERS
  staging/src/k8s.io/api/certificates/OWNERS
  staging/src/k8s.io/api/extensions/OWNERS
  staging/src/k8s.io/api/rbac/OWNERS
  staging/src/k8s.io/apimachinery/pkg/api/errors/OWNERS
  staging/src/k8s.io/apimachinery/pkg/api/resource/OWNERS
  staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  staging/src/k8s.io/apiserver/OWNERS
  staging/src/k8s.io/apiserver/pkg/endpoints/testing/OWNERS
  staging/src/k8s.io/apiserver/pkg/registry/generic/OWNERS
  staging/src/k8s.io/apiserver/pkg/registry/rest/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/S

#59734 Format some import statements in scheduler pkg
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/core/generic_scheduler.go
  pkg/scheduler/factory/plugins.go
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, sig/scheduling, size/XS

#56478 admissionregistration use shared informer instead of poll
  staging/src/k8s.io/apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apiserver/pkg/admission/configuration/BUILD
  staging/src/k8s.io/apiserver/pkg/admission/configuration/mutating_webhook_manager.go
  staging/src/k8s.io/apiserver/pkg/admission/configuration/mutating_webhook_manager_test.go
  staging/src/k8s.io/apiserver/pkg/admission/configuration/validating_webhook_manager.go
  staging/src/k8s.io/apiserver/pkg/admission/configuration/validating_webhook_manager_test.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/BUILD
  staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/admission.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/admission_test.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/BUILD
  staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/admission.go
  staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/admission_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note-none, sig/api-machinery, size/L

#59681 Ignore 0% and 100% eviction thresholds
  pkg/kubelet/apis/kubeletconfig/v1alpha1/types.go
  pkg/kubelet/eviction/helpers.go
  pkg/kubelet/eviction/helpers_test.go
  test/e2e_node/eviction_test.go
Labels: approved, area/kubelet, area/kubelet-api, cncf-cla: yes, lgtm, priority/important-soon, release-note, sig/node, size/M

#59653 Remove bootstrap kubelet config on reset
  cmd/kubeadm/app/cmd/reset.go
  cmd/kubeadm/app/preflight/checks.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, size/XS

#58812 Add HTTPProxyCheck to preflight checks for 'kubeadm join' subcommand
  cmd/kubeadm/app/preflight/checks.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, size/S

#59665 libffi-dev dependency added in fluentd-es-image Dockerfile to solve the docker build error
  cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59511 Add node e2e tests to verify HugePages feature
  test/e2e_node/BUILD
  test/e2e_node/hugepages_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#59818 Add reviewers to util/mount
  pkg/util/mount/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#59705 kubectl port-forward allows using resource name to select a matching pod
  pkg/kubectl/cmd/portforward.go
  pkg/kubectl/cmd/portforward_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/cli, size/M

#59207 build: fix a logic error in shell script.
  build/common.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59677 local-up-cluster.sh conformance tests - ALLOW_SECURITY_CONTEXT should default to true
  hack/local-up-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59803 Avoid hook errors when effecting label changes on kubernetes-worker charm.
  cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#59492 Remove experimental keystone authenticator
  cmd/kube-apiserver/app/options/options_test.go
  hack/.golint_failures
  pkg/kubeapiserver/authenticator/BUILD
  pkg/kubeapiserver/authenticator/config.go
  pkg/kubeapiserver/options/authentication.go
  staging/src/k8s.io/apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/BUILD
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/keystone/BUILD
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/keystone/doc.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/password/keystone/keystone.go
Labels: approved, cncf-cla: yes, lgtm, release-note-action-required, sig/auth, sig/openstack, size/L

#59691 Remove CSI plugin from ProbeExpandableVolumePlugins
  cmd/kube-controller-manager/app/plugins.go
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, release-note-none, sig/storage, size/XS

#59831 fix markdown formatting for test image doc
  test/images/resource-consumer/README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/S

#59828 Fix a race condition in SharedInformer
  staging/src/k8s.io/client-go/tools/cache/shared_informer.go
  staging/src/k8s.io/client-go/tools/cache/shared_informer_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#57106 Kubelet status manager sync the status of local Pods
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/kubelet_pods.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/node, size/S

#59530 Add a new environment variable to the gce startup scripts called KUBE_PROXY_MODE
  cluster/common.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper.sh
  hack/local-up-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59532 Route verify script output to stderr
  hack/verify-bazel.sh
  hack/verify-boilerplate.sh
  hack/verify-godep-licenses.sh
  hack/verify-godeps.sh
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59685 Extend timeout to deal with pkg/master flake.
  pkg/master/BUILD
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59797 Continue fixing bash scripts
  hack/grab-profiles.sh
  hack/update-codegen.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#57445 Build Kubernetes binaries with valid Semantic Version
  hack/lib/version.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59523 Revert "add number measurement for bound/unbound pv/pvc"
  pkg/controller/volume/persistentvolume/BUILD
  pkg/controller/volume/persistentvolume/metrics/BUILD
  pkg/controller/volume/persistentvolume/metrics/metrics.go
  pkg/controller/volume/persistentvolume/pv_controller_base.go
  test/e2e/framework/pv_util.go
  test/e2e/storage/BUILD
  test/e2e/storage/volume_metrics.go
Labels: approved, cncf-cla: yes, lgtm, priority/failing-test, release-note-none, size/L

#59090 Add e2e test for PV protection
  test/e2e/framework/pv_util.go
  test/e2e/framework/util.go
  test/e2e/storage/BUILD
  test/e2e/storage/pv_protection.go
  test/e2e/storage/pvc_protection.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/L

#59697 Update communication readme link to match new location.
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#59489 devicemanager testing: dynamically choose tmp dir
  pkg/kubelet/cm/devicemanager/manager_test.go
Labels: approved, area/hw-accelerators, cncf-cla: yes, lgtm, release-note-none, size/M

#59761 Removing Production Code usage from vSphere E2E tests
  test/e2e/storage/volumes.go
  test/e2e/storage/vsphere/BUILD
  test/e2e/storage/vsphere/bootstrap.go
  test/e2e/storage/vsphere/config.go
  test/e2e/storage/vsphere/nodemapper.go
  test/e2e/storage/vsphere/persistent_volumes-vsphere.go
  test/e2e/storage/vsphere/pv_reclaimpolicy.go
  test/e2e/storage/vsphere/pvc_label_selector.go
  test/e2e/storage/vsphere/vsphere.go
  test/e2e/storage/vsphere/vsphere_scale.go
  test/e2e/storage/vsphere/vsphere_statefulsets.go
  test/e2e/storage/vsphere/vsphere_stress.go
  test/e2e/storage/vsphere/vsphere_utils.go
  test/e2e/storage/vsphere/vsphere_volume_cluster_ds.go
  test/e2e/storage/vsphere/vsphere_volume_diskformat.go
  test/e2e/storage/vsphere/vsphere_volume_disksize.go
  test/e2e/storage/vsphere/vsphere_volume_fstype.go
  test/e2e/storage/vsphere/vsphere_volume_master_restart.go
  test/e2e/storage/vsphere/vsphere_volume_node_poweroff.go
  test/e2e/storage/vsphere/vsphere_volume_ops_storm.go
  test/e2e/storage/vsphere/vsphere_volume_perf.go
  test/e2e/storage/vsphere/vsphere_volume_placement.go
  test/e2e/storage/vsphere/vsphere_volume_vsan_policy.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#59837 juju: Fix broken ingress after upgrade-charm
  cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59103 Upload container runtime log to sd/es.
  cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml
  cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml
  cluster/addons/fluentd-gcp/fluentd-gcp-configmap.yaml
  cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml
  cluster/common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper.sh
  test/e2e/instrumentation/logging/stackdrvier/basic.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/instrumentation, sig/node, size/M

#58433 bugfix(mount): lstat with abs path of parent instead of '/..'
  pkg/util/mount/mount_linux.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, sig/node, sig/storage, size/XS

#59832 Fake docker-client assigns random IPs to containers
  pkg/kubelet/dockershim/docker_sandbox_test.go
  pkg/kubelet/dockershim/docker_service_test.go
  pkg/kubelet/dockershim/libdocker/fake_client.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59825 Remove unused DeltaFIFO compressor argument to NewDeltaFIFO
  staging/src/k8s.io/client-go/tools/cache/controller.go
  staging/src/k8s.io/client-go/tools/cache/controller_test.go
  staging/src/k8s.io/client-go/tools/cache/delta_fifo.go
  staging/src/k8s.io/client-go/tools/cache/delta_fifo_test.go
  staging/src/k8s.io/client-go/tools/cache/shared_informer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#59817 Add retries to PrepareNodes utility function
  test/e2e/framework/util.go
  test/integration/framework/perf_utils.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59711 Kubemark using cobra commands
  cmd/kubemark/BUILD
  cmd/kubemark/hollow-node.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59788 Fix typos
  pkg/controller/bootstrap/jws.go
  pkg/kubelet/server/portforward/websocket.go
  pkg/proxy/ipvs/proxier.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59846 rename func ValidatePodSecurityContext to ValidatePod
  pkg/security/podsecuritypolicy/provider.go
  pkg/security/podsecuritypolicy/provider_test.go
  pkg/security/podsecuritypolicy/types.go
  plugin/pkg/admission/security/podsecuritypolicy/admission.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/S

#59792 Juju deployments change basic auth password should keep admin in masters group
  cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59666 Secure Kubelet's componentconfig defaults while maintaining CLI compatibility
  cmd/kubeadm/app/apis/kubeadm/validation/validation_test.go
  cmd/kubelet/app/options/BUILD
  cmd/kubelet/app/options/options.go
  cmd/kubelet/app/server.go
  pkg/kubelet/apis/kubeletconfig/fuzzer/fuzzer.go
  pkg/kubelet/apis/kubeletconfig/helpers_test.go
  pkg/kubelet/apis/kubeletconfig/types.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/defaults.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/types.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.conversion.go
  pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.deepcopy.go
  pkg/kubemark/hollow_kubelet.go
Labels: approved, area/kubelet, area/kubelet-api, cncf-cla: yes, lgtm, priority/important-soon, release-note-action-required, sig/node, size/M

#56717 Dynamic client supports subresources
  staging/src/k8s.io/client-go/dynamic/client.go
  staging/src/k8s.io/client-go/dynamic/client_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/L

#59704 Automated cherry pick of #59607: Pass pvc namespace and annotations to Portworx Create API
  pkg/volume/portworx/portworx_util.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note, size/S

#59440 Use SetInformers method to register for Node events. (#449)
  pkg/cloudprovider/providers/vsphere/BUILD
  pkg/cloudprovider/providers/vsphere/vsphere.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#59891 Automated cherry pick of #59828: Add a test case for the race in #59822
  staging/src/k8s.io/client-go/tools/cache/shared_informer.go
  staging/src/k8s.io/client-go/tools/cache/shared_informer_test.go
Labels: approved, cherrypick-approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, sig/api-machinery, size/S, status/approved-for-milestone

#59878 Correct error strings and variable name.
  pkg/volume/glusterfs/glusterfs.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59852 Check if netstat or iproute2 is available
  hack/lib/etcd.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59335 Fixes volume predicate handler for equiv class
  pkg/scheduler/factory/BUILD
  pkg/scheduler/factory/factory.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/scheduling, size/M

#59872 Fixing diskIsAttached function
  test/e2e/storage/vsphere/vsphere_utils.go
  test/e2e/storage/vsphere/vsphere_volume_fstype.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59646 Add bound/unbound pv/pvc volume metrics
  pkg/controller/volume/persistentvolume/BUILD
  pkg/controller/volume/persistentvolume/metrics/BUILD
  pkg/controller/volume/persistentvolume/metrics/metrics.go
  pkg/controller/volume/persistentvolume/pv_controller_base.go
  test/e2e/framework/pv_util.go
  test/e2e/storage/BUILD
  test/e2e/storage/volume_metrics.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/L

#59588 Create pkg/kubelet/apis/deviceplugin/v1beta1 directory.
  hack/.golint_failures
  hack/update-generated-device-plugin-dockerized.sh
  hack/verify-generated-device-plugin.sh
  pkg/kubelet/apis/BUILD
  pkg/kubelet/apis/deviceplugin/v1beta1/BUILD
  pkg/kubelet/apis/deviceplugin/v1beta1/api.pb.go
  pkg/kubelet/apis/deviceplugin/v1beta1/api.proto
  pkg/kubelet/apis/deviceplugin/v1beta1/constants.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XXL

#59877 Standardize on KUBE_PROXY_MODE (not KUBEPROXY_MODE)
  hack/local-up-cluster.sh
  pkg/proxy/ipvs/README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59886 Partial revert of #59797
  hack/update-codegen.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59892 kubelet: revert the status HostIP behavior
  pkg/kubelet/kubelet_pods.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59657 Enable scaling fluentd-gcp resources using ScalingPolicy.
  cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml
  cluster/addons/fluentd-gcp/scaler-deployment.yaml
  cluster/addons/fluentd-gcp/scaler-policy.yaml
  cluster/addons/fluentd-gcp/scaler-rbac.yaml
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/gci/configure-helper.sh
Labels: approved, area/platform/gce, area/platform/gke, cncf-cla: yes, lgtm, release-note, size/L

#59899 apiserver: fix some typos from refactor
  staging/src/k8s.io/apiserver/pkg/server/config.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59871 Store labels and fields with object
  staging/src/k8s.io/apiserver/pkg/storage/cacher.go
  staging/src/k8s.io/apiserver/pkg/storage/watch_cache.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59921 fix fluentd-gcp-scaler to look at correct fluentd-gcp version
  cluster/addons/fluentd-gcp/scaler-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59630 Task 0: Added Alpha flag for NoDaemonSetScheduler feature.
  pkg/features/kube_features.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59323 add node shutdown taint
  pkg/cloudprovider/cloud.go
  pkg/cloudprovider/providers/aws/aws.go
  pkg/cloudprovider/providers/azure/azure_instances.go
  pkg/cloudprovider/providers/cloudstack/cloudstack_instances.go
  pkg/cloudprovider/providers/cloudstack/metadata.go
  pkg/cloudprovider/providers/fake/fake.go
  pkg/cloudprovider/providers/gce/gce_instances.go
  pkg/cloudprovider/providers/openstack/openstack_instances.go
  pkg/cloudprovider/providers/ovirt/ovirt.go
  pkg/cloudprovider/providers/photon/photon.go
  pkg/cloudprovider/providers/vsphere/vsphere.go
  pkg/controller/cloud/node_controller.go
  pkg/controller/cloud/node_controller_test.go
  pkg/controller/nodelifecycle/node_lifecycle_controller.go
  pkg/controller/nodelifecycle/node_lifecycle_controller_test.go
  pkg/controller/testutil/test_utils.go
  pkg/controller/util/node/controller_utils.go
  pkg/scheduler/algorithm/well_known_labels.go
  pkg/volume/cinder/attacher_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/azure, sig/scheduling, size/L

#59353 update name printer output to kind.group/name
  hack/make-rules/test-cmd-util.sh
  hack/testdata/CRD/resource.yaml
  pkg/kubectl/cmd/label.go
  pkg/kubectl/cmd/set/set_env_test.go
  pkg/kubectl/cmd/set/set_image_test.go
  pkg/kubectl/cmd/set/set_resources_test.go
  pkg/kubectl/cmd/set/set_selector_test.go
  pkg/kubectl/cmd/set/set_serviceaccount_test.go
  pkg/kubectl/cmd/util/factory_builder.go
  pkg/kubectl/cmd/util/printing.go
  pkg/kubectl/resource/builder.go
  pkg/printers/BUILD
  pkg/printers/internalversion/printers_test.go
  pkg/printers/name.go
  pkg/printers/printers.go
  staging/src/k8s.io/apimachinery/pkg/runtime/schema/group_version.go
  staging/src/k8s.io/client-go/discovery/restmapper.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#59905 Rename ConfigOK to KubeletConfigOk
  pkg/apis/core/types.go
  pkg/kubelet/kubeletconfig/configsync.go
  pkg/kubelet/kubeletconfig/controller.go
  pkg/kubelet/kubeletconfig/status/status.go
  pkg/kubelet/kubeletconfig/util/equal/equal.go
  staging/src/k8s.io/api/core/v1/types.go
  test/e2e_node/dynamic_kubelet_config_test.go
  test/e2e_node/util.go
Labels: approved, area/kubelet, area/kubelet-api, cncf-cla: yes, kind/api-change, lgtm, release-note, sig/node, size/L

#59887 Process existing cloud nodes in CCM
  pkg/controller/cloud/node_controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59937 Add a reviewer to addon-manager
  cluster/addons/addon-manager/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#59948 kubelet: revert the get pod with updated status
  pkg/kubelet/kubelet_getters.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59603 Automated cherry pick of #59539: Set instanceID to azure resource ID format while
  pkg/cloudprovider/providers/azure/azure_instances.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, size/XS

#59939 Avoid call to get cloud instances
  pkg/controller/cloud/node_controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59830 Azure - ARM Read/Write rate limiting
  pkg/cloudprovider/providers/azure/azure.go
  pkg/cloudprovider/providers/azure/azure_client.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#59754 Automated cherry pick of #59747: Map correct vmset name for internal load balancers
  pkg/cloudprovider/providers/azure/azure_util.go
  pkg/cloudprovider/providers/azure/azure_util_test.go
Labels: approved, approved-for-milestone, cherrypick-approved, cncf-cla: yes, kind/bug, lgtm, milestone/needs-approval, priority/important-soon, sig/azure, size/M

#59843 Automated cherry pick of #59671: Improve performance of scheduling queue by adding a hash
  plugin/pkg/scheduler/core/scheduling_queue.go
  plugin/pkg/scheduler/core/scheduling_queue_test.go
  plugin/pkg/scheduler/factory/factory.go
Labels: approved, approved-for-milestone, cherrypick-approved, cncf-cla: yes, kind/bug, lgtm, milestone/needs-approval, priority/important-soon, release-note-none, sig/scheduling, size/L

#59170 Fix kubelet PVC stale metrics
  pkg/kubelet/BUILD
  pkg/kubelet/kubelet.go
  pkg/kubelet/metrics/BUILD
  pkg/kubelet/metrics/collectors/BUILD
  pkg/kubelet/metrics/collectors/helper_test.go
  pkg/kubelet/metrics/collectors/volume_stats.go
  pkg/kubelet/metrics/collectors/volume_stats_test.go
  pkg/kubelet/metrics/metrics.go
  pkg/kubelet/server/stats/BUILD
  pkg/kubelet/server/stats/volume_stat_calculator.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/node, sig/storage, size/XL

#59453 Automated cherry pick of #59340: Ensure public IP removed after service deleted
  pkg/cloudprovider/providers/azure/azure_loadbalancer.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, sig/azure, size/XS

#59873 Fix DownwardAPI refresh race.
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator_test.go
  pkg/kubelet/volumemanager/volume_manager.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/node, sig/storage, size/S

#59933 gke-certificates-controller: rm -rf
  cmd/BUILD
  cmd/gke-certificates-controller/BUILD
  cmd/gke-certificates-controller/OWNERS
  cmd/gke-certificates-controller/app/BUILD
  cmd/gke-certificates-controller/app/gke_certificates_controller.go
  cmd/gke-certificates-controller/app/gke_signer.go
  cmd/gke-certificates-controller/app/gke_signer_test.go
  cmd/gke-certificates-controller/app/options.go
  cmd/gke-certificates-controller/main.go
  hack/.golint_failures
  hack/lib/golang.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#59923 Rework volume manager log levels
  pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go
  pkg/kubelet/volumemanager/reconciler/reconciler.go
  pkg/volume/util/operationexecutor/operation_executor.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/node, sig/storage, size/M

#59944 Update reviewers for sig-scheduling.
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scalability, sig/scheduling, size/XS

#59953 Fix pod scheduled.
  pkg/kubelet/kubelet_pods.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/node, size/XS

#59809 kubectl port-forward should resolve service port to target port
  pkg/kubectl/cmd/portforward.go
  pkg/kubectl/cmd/portforward_test.go
  pkg/kubectl/cmd/util/factory_object_mapping.go
  pkg/kubectl/util/BUILD
  pkg/kubectl/util/service_port.go
  pkg/kubectl/util/service_port_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/cli, sig/network, size/XL

#59955 Updating kubemci e2e test to not add kubeconfig flag for get-status
  test/e2e/framework/ingress_utils.go
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59808 use prometheus-to-sd 0.2.4 and fluentd-gcp-image 2.0.16
  cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
  cluster/addons/fluentd-gcp/event-exporter.yaml
  cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml
  cluster/addons/fluentd-gcp/scaler-deployment.yaml
  cluster/addons/metadata-proxy/gce/metadata-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#59913 Fix cluster autoscaler test to support regional clusters.
  test/e2e/autoscaling/cluster_size_autoscaling.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#59917 Add quotas to density and load tests
  test/e2e/scalability/density.go
  test/e2e/scalability/load.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scalability, size/M

#59668 Add AWS cloud provider option for IAM role
  pkg/cloudprovider/providers/aws/BUILD
  pkg/cloudprovider/providers/aws/aws.go
  pkg/cloudprovider/providers/aws/aws_test.go
  pkg/cloudprovider/providers/aws/regions_test.go
  pkg/cloudprovider/providers/aws/tags_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/aws, size/L

#59909 Add jsafrane as AWS approver.
  pkg/cloudprovider/providers/aws/OWNERS
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/XS

#59870 add an admission decorator chain
  staging/src/k8s.io/apiserver/pkg/admission/BUILD
  staging/src/k8s.io/apiserver/pkg/admission/decorator.go
  staging/src/k8s.io/apiserver/pkg/admission/plugins.go
  staging/src/k8s.io/apiserver/pkg/server/options/admission.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/M

#59914 csi: Remove stale volume path
  pkg/volume/csi/csi_mounter.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#57700 Improve the error message.
  staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59954 Index PVs by StorageClass in assume cache
  pkg/controller/volume/persistentvolume/scheduler_assume_cache.go
  pkg/controller/volume/persistentvolume/scheduler_assume_cache_test.go
  pkg/controller/volume/persistentvolume/scheduler_binder.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/L

#59707 Automated cherry pick of #59540: return error if New-SmbGlobalMapping failed in azure file
  pkg/util/mount/mount_windows.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, size/XS

#57136 Updated PID pressure node condition.
  pkg/kubelet/apis/stats/v1alpha1/types.go
  pkg/kubelet/eviction/api/types.go
  pkg/kubelet/eviction/eviction_manager.go
  pkg/kubelet/eviction/helpers.go
  pkg/kubelet/eviction/types.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_node_status_test.go
  pkg/kubelet/server/server_test.go
  pkg/kubelet/server/stats/handler.go
  pkg/kubelet/server/stats/summary.go
  pkg/kubelet/server/stats/summary_test.go
  pkg/kubelet/server/stats/testing/mock_stats_provider.go
  pkg/kubelet/stats/BUILD
  pkg/kubelet/stats/stats_provider.go
  pkg/kubelet/stats/stats_provider_linux.go
  pkg/kubelet/stats/stats_provider_unsupported.go
  staging/src/k8s.io/api/core/v1/types.go
  test/e2e_node/summary_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/node, size/L

#59920 Clean-up not needed method in juju charms
  cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#59769 Collect ephemeral storage capacity on initialization
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/kubelet.go
  pkg/kubelet/kubelet_node_status.go
  pkg/kubelet/kubelet_node_status_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note-none, sig/node, size/L

#59956 Wait for bound pvc metric updated before validating
  test/e2e/storage/volume_metrics.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/XS

#57885 Improve comments for kubelet
  pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go
  pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto
  pkg/kubelet/apis/deviceplugin/v1alpha/api.pb.go
  pkg/kubelet/apis/deviceplugin/v1alpha/api.proto
  pkg/kubelet/apis/deviceplugin/v1alpha/constants.go
  pkg/kubelet/cadvisor/testing/cadvisor_fake.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59827 Deprecate kubelet flag for cadvisor port
  cmd/kubelet/app/options/options.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, release-note, sig/node, size/XS

#59683 Remove unused getClusterCIDR()
  cmd/kubeadm/app/phases/addons/proxy/proxy.go
  cmd/kubeadm/app/phases/addons/proxy/proxy_test.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/S
