Repository kubernetes/kubernetes, pull requests merged in 2018-05, with the labels that each got.

#63178 scheduler: clean up and simplify equivalence cache locking
  pkg/scheduler/core/equivalence_cache.go
  pkg/scheduler/core/equivalence_cache_test.go
  pkg/scheduler/core/generic_scheduler.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, needs-ok-to-test, release-note-none, sig/scheduling, size/L

#63177 kubectl should not have a direct code dependency on controllers
  pkg/kubectl/BUILD
  pkg/kubectl/rollback.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63152 Revert "Revert "gce: move etcd dir cleanup to manifests""
  build/lib/release.sh
  cluster/addons/etcd-empty-dir-cleanup/podsecuritypolicies/etcd-empty-dir-cleanup-psp-binding.yaml
  cluster/addons/etcd-empty-dir-cleanup/podsecuritypolicies/etcd-empty-dir-cleanup-psp-role.yaml
  cluster/addons/etcd-empty-dir-cleanup/podsecuritypolicies/etcd-empty-dir-cleanup-psp.yaml
  cluster/gce/gci/BUILD
  cluster/gce/gci/configure-helper.sh
  cluster/gce/manifests/BUILD
  cluster/gce/manifests/etcd-empty-dir-cleanup.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63253 make dynamic client slightly easier to use and add fakes
  pkg/controller/namespace/deletion/namespaced_resources_deleter.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/registration_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/resources.go
  staging/src/k8s.io/client-go/dynamic/fake/BUILD
  staging/src/k8s.io/client-go/dynamic/fake/simple.go
  staging/src/k8s.io/client-go/dynamic/simple.go
  test/e2e/apimachinery/aggregator.go
  test/e2e/apimachinery/crd_watch.go
  test/e2e/apimachinery/garbage_collector.go
  test/e2e/framework/crd_util.go
  test/e2e/framework/util.go
  test/integration/garbagecollector/garbage_collector_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/L

#63299 Add version/group usage and example to kubectl get
  pkg/kubectl/cmd/get/get.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/cli, size/S

#63321 kubelet: force filterContainerID to empty string when removeAll is true
  pkg/kubelet/kubelet_pods.go
  pkg/kubelet/pod_container_deletor.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/node, size/XS

#63330 add test for sparse version encoding/decoding
  pkg/kubectl/scheme/BUILD
  pkg/kubectl/scheme/sparse_test.go
  staging/src/k8s.io/apimachinery/pkg/runtime/serializer/BUILD
  staging/src/k8s.io/apimachinery/pkg/runtime/serializer/sparse_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#62893 mark APIServiceSpec.CABundle optional
  api/openapi-spec/swagger.json
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto
  staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63138 Api server extra args
  cmd/kubeadm/app/phases/controlplane/manifests.go
  cmd/kubeadm/app/phases/controlplane/manifests_test.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/L

#63091 Set names for OpenStack loadbalancer members and monitors
  pkg/cloudprovider/providers/openstack/openstack_loadbalancer.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#63201 Enable bypassing online checks in kubeadm upgrade plan
  cmd/kubeadm/app/cmd/upgrade/common.go
  cmd/kubeadm/app/cmd/upgrade/plan.go
  cmd/kubeadm/app/phases/upgrade/compute_test.go
  cmd/kubeadm/app/phases/upgrade/versiongetter.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/L

#63341 Adds support for arm64 to microbot example of the kubernetes-worker charm.
  cluster/juju/layers/kubernetes-worker/actions/microbot
  cluster/juju/layers/kubernetes-worker/templates/microbot-example.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63335 update restmapping to indicate fully qualified resource
  pkg/controller/garbagecollector/operations.go
  pkg/controller/podautoscaler/horizontal.go
  pkg/controller/podautoscaler/horizontal_test.go
  pkg/controller/podautoscaler/metrics/rest_metrics_client_test.go
  pkg/controller/podautoscaler/replica_calculator_test.go
  pkg/kubectl/cmd/drain.go
  pkg/kubectl/cmd/rollout/rollout_history.go
  pkg/kubectl/cmd/rollout/rollout_pause.go
  pkg/kubectl/cmd/rollout/rollout_resume.go
  pkg/kubectl/cmd/run.go
  pkg/kubectl/cmd/scale.go
  pkg/kubectl/cmd/util/editor/editoptions.go
  pkg/kubectl/cmd/util/helpers.go
  pkg/kubectl/resource/builder.go
  pkg/kubectl/resource/builder_test.go
  pkg/kubectl/resource/helper.go
  pkg/kubectl/resource/result.go
  pkg/kubectl/resource/visitor.go
  pkg/printers/internalversion/describe.go
  plugin/pkg/admission/gc/gc_admission.go
  staging/src/k8s.io/apimachinery/pkg/api/meta/interfaces.go
  staging/src/k8s.io/apimachinery/pkg/api/meta/restmapper.go
  staging/src/k8s.io/apimachinery/pkg/api/meta/restmapper_test.go
  staging/src/k8s.io/metrics/pkg/client/custom_metrics/client.go
  test/integration/apiserver/print_test.go
  test/integration/etcd/etcd_storage_path_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/L

#63308 Add set image test for sparse API group resource
  hack/make-rules/test-cmd-util.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/cli, size/S

#61833 check for commands in kubelet command line
  cmd/kubelet/app/server.go
Labels: approved, area/kubelet, cncf-cla: yes, lgtm, release-note-none, size/XS

#62062 not expose object detail when creating TokenRequest
  pkg/registry/core/serviceaccount/storage/token.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#62918 Expose openapi spec to API handlers
  staging/BUILD
  staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apimachinery/Godeps/Godeps.json
  staging/src/k8s.io/apimachinery/pkg/runtime/BUILD
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/BUILD
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/cacher.go
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/cacher_test.go
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/interfaces.go
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/parser.go
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/parser_test.go
  staging/src/k8s.io/apimachinery/pkg/runtime/openapi/resource.go
  staging/src/k8s.io/apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apiserver/pkg/endpoints/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/groupversion.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/BUILD
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go
  staging/src/k8s.io/apiserver/pkg/endpoints/installer.go
  staging/src/k8s.io/apiserver/pkg/server/BUILD
  staging/src/k8s.io/apiserver/pkg/server/config.go
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
  staging/src/k8s.io/apiserver/pkg/server/routes/openapi.go
  staging/src/k8s.io/apiserver/pkg/util/downloader/BUILD
  staging/src/k8s.io/apiserver/pkg/util/downloader/downloader.go
  staging/src/k8s.io/apiserver/pkg/util/downloader/downloader_test.go
  staging/src/k8s.io/apiserver/pkg/util/downloader/responsewriter.go
  staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/BUILD
  staging/src/k8s.io/kube-aggregator/pkg/controllers/openapi/downloader.go
  staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XXL

#59254 Add UT test for PolicyRuleBuilder
  pkg/apis/rbac/helpers_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/auth, size/L

#63349 Decorator for Create should be called on out, not obj
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go
  staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/S

#63294 Add metric for throttled requests in AWS
  pkg/cloudprovider/providers/aws/aws.go
  pkg/cloudprovider/providers/aws/aws_metrics.go
  pkg/cloudprovider/providers/aws/retry_handler.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/aws, size/M

#63380 Revert "apiserver: change default reconciler to LeaseEndpoint"
  cmd/kube-apiserver/app/options/options.go
  cmd/kube-apiserver/app/options/options_test.go
Labels: approved, cncf-cla: yes, lgtm, queue/fix, release-note-none, retest-not-required, size/XS

#62060 fix namespace miss bug
  hack/make-rules/test-cmd-util.sh
  pkg/kubectl/cmd/get/get.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#62516 [GCE] Add new formats to resource parser and self link creator
  pkg/cloudprovider/providers/gce/cloud/gen.go
  pkg/cloudprovider/providers/gce/cloud/gen/main.go
  pkg/cloudprovider/providers/gce/cloud/gen_test.go
  pkg/cloudprovider/providers/gce/cloud/meta/service.go
  pkg/cloudprovider/providers/gce/cloud/utils.go
  pkg/cloudprovider/providers/gce/cloud/utils_test.go
  pkg/cloudprovider/providers/gce/gce_loadbalancer_internal_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#62892 add index to node-authorizer for high cardinality vertices
  plugin/pkg/auth/authorizer/node/BUILD
  plugin/pkg/auth/authorizer/node/graph.go
  plugin/pkg/auth/authorizer/node/graph_test.go
  plugin/pkg/auth/authorizer/node/intset.go
  plugin/pkg/auth/authorizer/node/intset_test.go
  plugin/pkg/auth/authorizer/node/node_authorizer.go
  plugin/pkg/auth/authorizer/node/node_authorizer_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63278 Use new Azure SDK APIs for load balancer and public IP operations
  pkg/cloudprovider/providers/azure/azure_backoff.go
  pkg/cloudprovider/providers/azure/azure_client.go
  pkg/cloudprovider/providers/azure/azure_fakes.go
  pkg/cloudprovider/providers/azure/azure_loadbalancer.go
  pkg/cloudprovider/providers/azure/azure_test.go
  pkg/cloudprovider/providers/azure/azure_wrap.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#62903 Add more volume types in e2e and fix part of them.
  pkg/kubelet/cm/container_manager_linux_test.go
  pkg/util/mount/exec_mount.go
  pkg/util/mount/exec_mount_test.go
  pkg/util/mount/exec_mount_unsupported.go
  pkg/util/mount/fake.go
  pkg/util/mount/mount.go
  pkg/util/mount/mount_linux.go
  pkg/util/mount/mount_linux_test.go
  pkg/util/mount/mount_unsupported.go
  pkg/util/mount/mount_windows.go
  pkg/util/mount/nsenter_mount.go
  pkg/util/mount/nsenter_mount_unsupported.go
  pkg/util/nsenter/nsenter.go
  pkg/util/removeall/removeall_test.go
  pkg/volume/host_path/host_path_test.go
  pkg/volume/local/local.go
  pkg/volume/rbd/rbd.go
  pkg/volume/volume_linux.go
  pkg/volume/volume_unsupported.go
  test/e2e/storage/persistent_volumes-local.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63375 ensure diff output includes the portion that differs
  staging/src/k8s.io/apimachinery/pkg/util/diff/diff.go
  staging/src/k8s.io/apimachinery/pkg/util/diff/diff_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63213 Implements OIDC distributed claims.
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/BUILD
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc.go
  staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/auth, size/XL

#61725 Pod deletion can be contended, causing test failure
  test/e2e/node/pods.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/node, size/XS

#63261 Use cloudprovider.NotImplemented in AddSSHKeyToAllInstances
  pkg/cloudprovider/providers/azure/azure_instances.go
  pkg/cloudprovider/providers/cloudstack/cloudstack_instances.go
  pkg/cloudprovider/providers/cloudstack/metadata.go
  pkg/volume/cinder/attacher_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63377 juju: Make kubernetes-master status handling more robust
  cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63227 Fix ensure by provider id
  pkg/controller/cloud/node_controller.go
  pkg/controller/cloud/node_controller_test.go
Labels: approved, area/cloudprovider, cncf-cla: yes, lgtm, release-note-none, size/M

#63073 refactor device plugin grpc dial with dialcontext
  pkg/kubelet/cm/devicemanager/device_plugin_stub.go
  pkg/kubelet/cm/devicemanager/endpoint.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#63376 don't reuse resource builder in describe
  pkg/kubectl/cmd/describe.go
  pkg/kubectl/resource/builder.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/cli, size/S

#63392 Fix test "should fail due to non-existent path" under gce-slow
  test/e2e/storage/persistent_volumes-local.go
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, release-note-none, size/XS

#56137 remove punctuation from the end of an error string
  pkg/kubectl/run.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, lifecycle/rotten, release-note-none, size/XS

#62541 Use a []string for CgroupName, which is a more accurate internal representation
  pkg/kubelet/cm/cgroup_manager_linux.go
  pkg/kubelet/cm/cgroup_manager_linux_test.go
  pkg/kubelet/cm/cgroup_manager_unsupported.go
  pkg/kubelet/cm/container_manager_linux.go
  pkg/kubelet/cm/node_container_manager.go
  pkg/kubelet/cm/pod_container_manager_linux.go
  pkg/kubelet/cm/pod_container_manager_stub.go
  pkg/kubelet/cm/qos_container_manager_linux.go
  pkg/kubelet/cm/types.go
  pkg/kubelet/dockershim/BUILD
  pkg/kubelet/dockershim/docker_service.go
  pkg/kubelet/stats/cadvisor_stats_provider.go
  test/e2e_node/hugepages_test.go
  test/e2e_node/node_container_manager_test.go
  test/e2e_node/pods_container_manager_test.go
  test/e2e_node/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#61940 Add support for CNI on Windows Server 2016 RTM
  pkg/kubelet/dockershim/helpers_windows.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63098 aws, azure: replace path with filepath
  pkg/volume/aws_ebs/aws_ebs.go
  pkg/volume/aws_ebs/aws_ebs_block.go
  pkg/volume/aws_ebs/aws_ebs_block_test.go
  pkg/volume/aws_ebs/aws_ebs_test.go
  pkg/volume/azure_dd/attacher.go
  pkg/volume/azure_dd/azure_common.go
  pkg/volume/azure_dd/azure_common_linux.go
  pkg/volume/azure_file/azure_file_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/storage, size/M

#63258 stop using Info.Mappings when they may not be present
  pkg/kubectl/cmd/BUILD
  pkg/kubectl/cmd/label.go
  pkg/kubectl/cmd/taint.go
  pkg/kubectl/cmd/util/helpers.go
  pkg/kubectl/resource/visitor.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63398 remove unnessary kubectl conversions
  pkg/kubectl/cmd/apply_set_last_applied.go
  pkg/kubectl/cmd/util/editor/editoptions.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/cli, size/M

#63403 don't block creation on lack of delete powers
  plugin/pkg/admission/gc/gc_admission.go
  plugin/pkg/admission/gc/gc_admission_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/api-machinery, size/M

#61455 Deprecate repair-malformed-updates flag, move object meta mutation into BeforeCreate
  cmd/kube-apiserver/app/options/BUILD
  cmd/kube-apiserver/app/options/options.go
  pkg/apis/core/validation/validation.go
  pkg/apis/core/validation/validation_test.go
  pkg/registry/core/service/storage/rest.go
  staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
  staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta_test.go
  staging/src/k8s.io/apiserver/pkg/registry/rest/update.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/L

#63231 Automated cherry pick of #63118: Fix race between stopping old and starting new endpoint
  pkg/kubelet/cm/deviceplugin/manager.go
Labels: approved, cherrypick-approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, release-note, sig/node, size/XS, status/approved-for-milestone

#63312 remove unnecessary encoder
  pkg/kubectl/cmd/get/humanreadable_flags.go
  pkg/kubectl/cmd/rollingupdate.go
  pkg/kubectl/cmd/util/printing.go
  pkg/printers/humanreadable.go
  pkg/printers/internalversion/printers_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/cli, size/M

#63407 GCE: Pass certificate URLs instead of the certificate structs
  pkg/cloudprovider/providers/gce/gce_targetproxy.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63339 kubelet: volume: do not create event on mount success
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/node, sig/storage, size/XS

#63399 use TempDir func in mount_windows_test.go
  pkg/util/mount/mount_windows_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63405 Update to latest Gophercloud
  Godeps/Godeps.json
  staging/src/k8s.io/client-go/Godeps/Godeps.json
  vendor/github.com/gophercloud/gophercloud/errors.go
  vendor/github.com/gophercloud/gophercloud/openstack/client.go
  vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/flavors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/endpoint_location.go
  vendor/github.com/gophercloud/gophercloud/openstack/identity/v3/tokens/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/floatingips/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/layer3/routers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/listeners/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/loadbalancers/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/monitors/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/lbaas_v2/pools/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/groups/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/security/rules/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/networks/results.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/requests.go
  vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/ports/results.go
  vendor/github.com/gophercloud/gophercloud/provider_client.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#63421 Cache preferred resources, use in kubectl resource name autocomplete
  pkg/kubectl/cmd/annotate.go
  pkg/kubectl/cmd/apiresources.go
  pkg/kubectl/cmd/apply_edit_last_applied.go
  pkg/kubectl/cmd/apply_view_last_applied.go
  pkg/kubectl/cmd/cmd.go
  pkg/kubectl/cmd/delete.go
  pkg/kubectl/cmd/edit.go
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/cmd/label.go
  pkg/kubectl/cmd/patch.go
  pkg/kubectl/cmd/util/cached_discovery.go
  pkg/kubectl/cmd/util/printing.go
  staging/src/k8s.io/client-go/discovery/cached/memcache.go
  staging/src/k8s.io/client-go/discovery/discovery_client.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, sig/cli, size/M

#63432 slim printer interface down to printing
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/sorter.go
  pkg/printers/customcolumn.go
  pkg/printers/humanreadable.go
  pkg/printers/interface.go
  pkg/printers/internalversion/printers_test.go
  pkg/printers/json.go
  pkg/printers/jsonpath.go
  pkg/printers/name.go
  pkg/printers/template.go
  pkg/printers/versioned.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63438 Use single struct in internal type to reduce difference with external type
  pkg/apis/extensions/v1beta1/zz_generated.conversion.go
  pkg/apis/policy/types.go
  pkg/apis/policy/v1beta1/zz_generated.conversion.go
  pkg/apis/policy/validation/validation.go
  pkg/apis/policy/validation/validation_test.go
  pkg/apis/policy/zz_generated.deepcopy.go
  pkg/printers/internalversion/describe.go
  pkg/security/podsecuritypolicy/group/mustrunas.go
  pkg/security/podsecuritypolicy/group/mustrunas_test.go
  pkg/security/podsecuritypolicy/provider_test.go
  pkg/security/podsecuritypolicy/user/mustrunas_test.go
  pkg/security/podsecuritypolicy/util/util.go
  plugin/pkg/admission/security/podsecuritypolicy/admission_test.go
Labels: approved, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, release-note-none, sig/auth, size/L

#63315 Fix pkg_rpm rules for bazel 0.13+
  build/root/WORKSPACE
  build/rpms/BUILD
  build/rpms/kubeadm.spec
  build/rpms/kubectl.spec
  build/rpms/kubelet.spec
  build/rpms/kubernetes-cni.spec
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#63383 Re-enable lease reconciler, fix shutdown race
  cmd/kube-apiserver/app/options/options.go
  cmd/kube-apiserver/app/options/options_test.go
  hack/update-openapi-spec.sh
  pkg/master/controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#63318 drive resourcebuilder from kubeconfig, allow scheme specification
  pkg/kubectl/cmd/BUILD
  pkg/kubectl/cmd/apply.go
  pkg/kubectl/cmd/attach.go
  pkg/kubectl/cmd/auth/reconcile.go
  pkg/kubectl/cmd/autoscale.go
  pkg/kubectl/cmd/certificates.go
  pkg/kubectl/cmd/clusterinfo.go
  pkg/kubectl/cmd/convert.go
  pkg/kubectl/cmd/create/BUILD
  pkg/kubectl/cmd/create/create.go
  pkg/kubectl/cmd/create/create_quota_test.go
  pkg/kubectl/cmd/delete.go
  pkg/kubectl/cmd/drain.go
  pkg/kubectl/cmd/edit_test.go
  pkg/kubectl/cmd/expose.go
  pkg/kubectl/cmd/expose_test.go
  pkg/kubectl/cmd/logs.go
  pkg/kubectl/cmd/portforward.go
  pkg/kubectl/cmd/rollout/rollout_history.go
  pkg/kubectl/cmd/rollout/rollout_pause.go
  pkg/kubectl/cmd/rollout/rollout_resume.go
  pkg/kubectl/cmd/rollout/rollout_status.go
  pkg/kubectl/cmd/rollout/rollout_undo.go
  pkg/kubectl/cmd/run.go
  pkg/kubectl/cmd/set/BUILD
  pkg/kubectl/cmd/set/set_env.go
  pkg/kubectl/cmd/set/set_env_test.go
  pkg/kubectl/cmd/set/set_image.go
  pkg/kubectl/cmd/set/set_image_test.go
  pkg/kubectl/cmd/set/set_resources.go
  pkg/kubectl/cmd/set/set_selector.go
  pkg/kubectl/cmd/set/set_serviceaccount.go
  pkg/kubectl/cmd/set/set_subject.go
  pkg/kubectl/cmd/taint.go
  pkg/kubectl/cmd/testing/BUILD
  pkg/kubectl/cmd/testing/fake.go
  pkg/kubectl/cmd/util/editor/editoptions.go
  pkg/kubectl/cmd/util/factory.go
  pkg/kubectl/cmd/util/factory_builder.go
  pkg/kubectl/cmd/util/factory_client_access.go
  pkg/kubectl/cmd/util/factory_object_mapping.go
  pkg/kubectl/cmd/util/factory_test.go
  pkg/kubectl/resource/BUILD
  pkg/kubectl/resource/builder.go
  pkg/kubectl/resource/builder_test.go
  pkg/kubectl/resource/client.go
  pkg/kubectl/resource/interfaces.go
  pkg/kubectl/resource/mapper.go
  pkg/kubectl/resource/result.go
  pkg/kubectl/resource/visitor.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#63439 compute configmap/secret key correctly cross-platform
  pkg/kubectl/util/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/cli, size/XS

#62990 Add dynamic RESTMapper to ControllerContext and make it generic
  cmd/kube-controller-manager/app/autoscaling.go
  cmd/kube-controller-manager/app/controllermanager.go
  cmd/kube-controller-manager/app/core.go
  test/integration/garbagecollector/garbage_collector_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63412 Update to go1.10.2
  build/build-image/cross/Dockerfile
  build/build-image/cross/VERSION
  build/root/WORKSPACE
  hack/lib/golang.sh
  test/images/Makefile
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#63114 Add MAX_PODS env allowing kubelet to be max-pods aware.
  cluster/gce/config-common.sh
  cluster/gce/config-default.sh
  cluster/gce/config-test.sh
  cluster/gce/util.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#61970 controller/endpoint: explict log msg when syncing error
  pkg/controller/endpoint/endpoints_controller.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#62712 fix ipvs firewall rules for loadbalancer type service
  pkg/proxy/ipvs/ipset.go
  pkg/proxy/ipvs/proxier.go
  pkg/proxy/ipvs/proxier_test.go
Labels: approved, area/ipvs, cncf-cla: yes, lgtm, release-note-none, size/L

#63425 Clean up Azure clients
  pkg/cloudprovider/providers/azure/azure_backoff.go
  pkg/cloudprovider/providers/azure/azure_client.go
  pkg/cloudprovider/providers/azure/azure_fakes.go
  pkg/cloudprovider/providers/azure/azure_routes.go
  pkg/cloudprovider/providers/azure/azure_standard.go
  pkg/cloudprovider/providers/azure/azure_test.go
  pkg/cloudprovider/providers/azure/azure_vmss.go
  pkg/cloudprovider/providers/azure/azure_wrap.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/azure, size/XL

#61154 catch err when Watch testResource failed in func TestWatchCallNonNamespace
  staging/src/k8s.io/client-go/testing/fixture_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#62981 Remove incomplete uint64 support from JSON unmarshaling
  staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  staging/src/k8s.io/apimachinery/pkg/apis/meta/fuzzer/fuzzer.go
  staging/src/k8s.io/apimachinery/pkg/apis/meta/v1beta1/deepcopy.go
  staging/src/k8s.io/apimachinery/pkg/runtime/converter.go
  staging/src/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note-none, sig/api-machinery, size/M

#55476 apiserver: document how to run sample-apiserver standalone outside the cluster
  staging/src/k8s.io/sample-apiserver/README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, retest-not-required-docs-only, size/M

#63460 Don't panic if admission options is nil
  staging/src/k8s.io/apiserver/pkg/server/options/admission.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63481 remove redundant runtime.GOMAXPROCS
  staging/src/k8s.io/apiextensions-apiserver/main.go
  staging/src/k8s.io/kube-aggregator/main.go
  staging/src/k8s.io/sample-apiserver/main.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#62914 kubelet: fix flake in TestUpdateExistingNodeStatusTimeout
  pkg/kubelet/kubelet_node_status_test.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, sig/node, size/XS

#63431 use new dynamic client
  cmd/kubeadm/app/util/apiclient/clientbacked_dryrun.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/M

#63496 Improve test coverage of Kubelet file utils
  pkg/kubelet/kubeletconfig/util/files/files.go
  pkg/kubelet/kubeletconfig/util/files/files_test.go
Labels: approved, area/kubelet, cncf-cla: yes, kind/feature, lgtm, release-note-none, sig/node, size/L

#63340 Remove cmdutil printer helpers
  pkg/kubectl/cmd/apiresources.go
  pkg/kubectl/cmd/apply_set_last_applied.go
  pkg/kubectl/cmd/apply_test.go
  pkg/kubectl/cmd/auth/BUILD
  pkg/kubectl/cmd/auth/auth.go
  pkg/kubectl/cmd/auth/cani.go
  pkg/kubectl/cmd/auth/cani_test.go
  pkg/kubectl/cmd/auth/reconcile.go
  pkg/kubectl/cmd/certificates.go
  pkg/kubectl/cmd/cmd.go
  pkg/kubectl/cmd/config/BUILD
  pkg/kubectl/cmd/config/config.go
  pkg/kubectl/cmd/config/config_test.go
  pkg/kubectl/cmd/config/flags.go
  pkg/kubectl/cmd/config/get_contexts.go
  pkg/kubectl/cmd/config/get_contexts_test.go
  pkg/kubectl/cmd/config/view.go
  pkg/kubectl/cmd/config/view_test.go
  pkg/kubectl/cmd/delete.go
  pkg/kubectl/cmd/delete_test.go
  pkg/kubectl/cmd/replace.go
  pkg/kubectl/cmd/scale.go
  pkg/kubectl/cmd/util/printing.go
  pkg/printers/BUILD
  pkg/printers/flags.go
  pkg/printers/internalversion/printers_test.go
  pkg/printers/printers.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#63266 gcp: allow non-bootstrap kubeconfig
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#62443 kubectl get CRD resources with --server-print=true column name error
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/tableconvertor/tableconvertor.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63519 [e2e ingress-gce] Change ingress-upgrade test to not check for number of instances
  test/e2e/upgrades/ingress.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63323 gce: plumb --kubelet-certificate-authority flag to apiserver
  cluster/gce/gci/configure-helper.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63517 //hack:update-mirror: ensure last URL in list is mirrored too
  build/workspace_mirror.bzl
  hack/update-workspace-mirror.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63045 passthrough readOnly to subpath
  pkg/kubelet/kubelet_pods.go
  pkg/util/mount/exec_mount_test.go
  pkg/util/mount/fake.go
  pkg/util/mount/mount.go
  pkg/util/mount/mount_linux.go
  pkg/util/mount/mount_linux_test.go
  test/e2e/storage/subpath.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/storage, size/L

#63472 Cleanup Pods in TestNominatedNodeCleanUp.
  test/integration/scheduler/preemption_test.go
  test/integration/scheduler/util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scheduling, size/M

#63264 Increase scheduler cache generation number monotonically in order to avoid collision
  pkg/scheduler/schedulercache/cache_test.go
  pkg/scheduler/schedulercache/node_info.go
  pkg/scheduler/schedulercache/node_info_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/scheduling, size/M, status/approved-for-milestone

#63415 Clean up kubelet eviction events
  pkg/kubelet/eviction/BUILD
  pkg/kubelet/eviction/api/types.go
  pkg/kubelet/eviction/eviction_manager.go
  pkg/kubelet/eviction/helpers.go
  pkg/kubelet/eviction/helpers_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-longterm, release-note-none, sig/node, size/L

#63489 cleaning up load balancer resources
  test/e2e/network/service.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63369 Automated cherry pick of #61002: IsNotFound should check ErrDefault404 and
  pkg/cloudprovider/providers/openstack/openstack.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note-none, size/S

#63291 clean unused variables
  pkg/kubectl/cmd/config/set.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63490 default the ignorenotfound for delete when selecting objects
  pkg/kubectl/cmd/delete.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#60445 Fixes fake client generation for non-namespaced subresources
  staging/src/k8s.io/client-go/testing/actions.go
  staging/src/k8s.io/code-generator/_examples/crd/apis/example/v1/types.go
  staging/src/k8s.io/code-generator/_examples/crd/apis/example/v1/zz_generated.deepcopy.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/clustertesttype.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/example_client.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/fake/fake_clustertesttype.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/fake/fake_example_client.go
  staging/src/k8s.io/code-generator/_examples/crd/clientset/versioned/typed/example/v1/generated_expansion.go
  staging/src/k8s.io/code-generator/_examples/crd/informers/externalversions/example/v1/clustertesttype.go
  staging/src/k8s.io/code-generator/_examples/crd/informers/externalversions/example/v1/interface.go
  staging/src/k8s.io/code-generator/_examples/crd/informers/externalversions/generic.go
  staging/src/k8s.io/code-generator/_examples/crd/listers/example/v1/clustertesttype.go
  staging/src/k8s.io/code-generator/_examples/crd/listers/example/v1/expansion_generated.go
  staging/src/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XL

#63507 move client based restmappers to client-go
  cmd/kube-apiserver/app/BUILD
  cmd/kube-apiserver/app/server.go
  cmd/kube-controller-manager/app/BUILD
  cmd/kube-controller-manager/app/controllermanager.go
  pkg/kubectl/BUILD
  pkg/kubectl/cmd/apply_test.go
  pkg/kubectl/cmd/autoscale.go
  pkg/kubectl/cmd/expose.go
  pkg/kubectl/cmd/rollout/rollout_history.go
  pkg/kubectl/cmd/rollout/rollout_pause.go
  pkg/kubectl/cmd/rollout/rollout_resume.go
  pkg/kubectl/cmd/rollout/rollout_status.go
  pkg/kubectl/cmd/rollout/rollout_undo.go
  pkg/kubectl/cmd/scale.go
  pkg/kubectl/cmd/taint.go
  pkg/kubectl/cmd/testing/BUILD
  pkg/kubectl/cmd/testing/fake.go
  pkg/kubectl/cmd/util/BUILD
  pkg/kubectl/cmd/util/factory_object_mapping.go
  pkg/kubectl/cmd/util/factory_test.go
  pkg/kubectl/kubectl.go
  staging/BUILD
  staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/etcd_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/BUILD
  staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/resources.go
  staging/src/k8s.io/client-go/discovery/BUILD
  staging/src/k8s.io/client-go/discovery/unstructured.go
  staging/src/k8s.io/client-go/restmapper/BUILD
  staging/src/k8s.io/client-go/restmapper/discovery.go
  staging/src/k8s.io/client-go/restmapper/discovery_test.go
  staging/src/k8s.io/client-go/restmapper/shortcut.go
  staging/src/k8s.io/client-go/restmapper/shortcut_test.go
  staging/src/k8s.io/client-go/scale/BUILD
  staging/src/k8s.io/client-go/scale/client_test.go
  test/e2e/framework/BUILD
  test/e2e/framework/framework.go
  test/e2e/scalability/BUILD
  test/e2e/scalability/load.go
  test/integration/etcd/BUILD
  test/integration/etcd/etcd_storage_path_test.go
  test/integration/garbagecollector/BUILD
  test/integration/garbagecollector/garbage_collector_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/api-machinery, size/XL

#63070 Refactor hard code in rest_test.go
  staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63536 use IOStreams for cli commands
  pkg/kubectl/cmd/alpha.go
  pkg/kubectl/cmd/apply.go
  pkg/kubectl/cmd/attach.go
  pkg/kubectl/cmd/attach_test.go
  pkg/kubectl/cmd/cmd.go
  pkg/kubectl/cmd/cp.go
  pkg/kubectl/cmd/delete.go
  pkg/kubectl/cmd/delete_flags.go
  pkg/kubectl/cmd/delete_test.go
  pkg/kubectl/cmd/diff.go
  pkg/kubectl/cmd/diff_test.go
  pkg/kubectl/cmd/exec.go
  pkg/kubectl/cmd/exec_test.go
  pkg/kubectl/cmd/logs.go
  pkg/kubectl/cmd/logs_test.go
  pkg/kubectl/cmd/plugin.go
  pkg/kubectl/cmd/plugin_test.go
  pkg/kubectl/cmd/portforward.go
  pkg/kubectl/cmd/portforward_test.go
  pkg/kubectl/cmd/proxy.go
  pkg/kubectl/cmd/replace.go
  pkg/kubectl/cmd/replace_test.go
  pkg/kubectl/cmd/run.go
  pkg/kubectl/cmd/run_test.go
  pkg/kubectl/cmd/top.go
  pkg/kubectl/cmd/top_node.go
  pkg/kubectl/cmd/top_node_test.go
  pkg/kubectl/cmd/top_pod.go
  pkg/kubectl/cmd/top_pod_test.go
  pkg/kubectl/cmd/top_test.go
  pkg/kubectl/plugins/BUILD
  pkg/kubectl/plugins/runner.go
  pkg/kubectl/plugins/runner_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#63526 adding support for VM name with extra Separator String
  pkg/cloudprovider/providers/azure/azure_vmss_cache.go
  pkg/cloudprovider/providers/azure/azure_vmss_cache_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/azure, size/S, status/approved-for-milestone

#63464 vsphere: use vim25.Client directly to support token authentication
  pkg/cloudprovider/providers/vsphere/BUILD
  pkg/cloudprovider/providers/vsphere/nodemanager.go
  pkg/cloudprovider/providers/vsphere/vclib/BUILD
  pkg/cloudprovider/providers/vsphere/vclib/connection.go
  pkg/cloudprovider/providers/vsphere/vclib/constants.go
  pkg/cloudprovider/providers/vsphere/vclib/datacenter.go
  pkg/cloudprovider/providers/vsphere/vclib/datacenter_test.go
  pkg/cloudprovider/providers/vsphere/vclib/datastore_test.go
  pkg/cloudprovider/providers/vsphere/vclib/folder_test.go
  pkg/cloudprovider/providers/vsphere/vclib/utils_test.go
  pkg/cloudprovider/providers/vsphere/vclib/virtualmachine.go
  pkg/cloudprovider/providers/vsphere/vclib/virtualmachine_test.go
  pkg/cloudprovider/providers/vsphere/vsphere.go
  pkg/cloudprovider/providers/vsphere/vsphere_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/vmware, size/L

#63535 Bump Heapster to v1.5.3
  cluster/addons/cluster-monitoring/google/heapster-controller.yaml
  cluster/addons/cluster-monitoring/googleinfluxdb/heapster-controller-combined.yaml
  cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml
  cluster/addons/cluster-monitoring/stackdriver/heapster-controller.yaml
  cluster/addons/cluster-monitoring/standalone/heapster-controller.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#63528 Build image size map upon node info updates
  pkg/scheduler/algorithm/priorities/image_locality.go
  pkg/scheduler/schedulercache/cache_test.go
  pkg/scheduler/schedulercache/node_info.go
  pkg/scheduler/schedulercache/node_info_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scheduling, size/M

#63297 Fix commands running crictl
  cmd/kubeadm/app/cmd/reset.go
  cmd/kubeadm/app/preflight/checks.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/M

#61883 set right Content-Type for configz
  pkg/util/configz/configz.go
  pkg/util/configz/configz_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#58580 Admit BestEffort if it tolerates memory pressure.
  pkg/kubelet/eviction/BUILD
  pkg/kubelet/eviction/eviction_manager.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/node, size/S

#63120 -Remove TODO comment of GetNonzeroRequests function
  pkg/scheduler/algorithm/priorities/util/non_zero.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scheduling, size/XS

#63516 1.10: Automated cherry pick of #63392
  test/e2e/storage/persistent_volumes-local.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63563 Fix cgroup names in node_container_manager_test.
  test/e2e_node/node_container_manager_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63541 Do not check vmSetName when getting Azure node's IP
  pkg/cloudprovider/providers/azure/azure_fakes.go
  pkg/cloudprovider/providers/azure/azure_routes_test.go
  pkg/cloudprovider/providers/azure/azure_standard.go
  pkg/cloudprovider/providers/azure/azure_vmsets.go
  pkg/cloudprovider/providers/azure/azure_vmss.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, release-note, sig/azure, size/M

#62453 Supported nodeSelector.matchFields in scheduler.
  pkg/scheduler/algorithm/BUILD
  pkg/scheduler/algorithm/predicates/BUILD
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/predicates/predicates_test.go
  pkg/scheduler/algorithm/types.go
  pkg/scheduler/algorithm/well_known_labels.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/scheduling, size/L

#63537 Return error when has no RequestInfo in handlerchain
  staging/src/k8s.io/apiserver/pkg/server/filters/BUILD
  staging/src/k8s.io/apiserver/pkg/server/filters/waitgroup.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63385 [CustomResourceSubresources] fix status subresource
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/BUILD
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy_test.go
Labels: approved, area/custom-resources, cncf-cla: yes, kind/bug, lgtm, release-note, size/L

#59034 [RBD block device ]ignore the loopbackdevice error, or the rbd volume will not get detached
  pkg/volume/rbd/rbd.go
  pkg/volume/util/operationexecutor/operation_generator.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63565 Bump kube-openapi dependency
  Godeps/Godeps.json
  staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apimachinery/Godeps/Godeps.json
  staging/src/k8s.io/apiserver/Godeps/Godeps.json
  staging/src/k8s.io/client-go/Godeps/Godeps.json
  staging/src/k8s.io/code-generator/Godeps/Godeps.json
  staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json
  staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/sample-controller/Godeps/Godeps.json
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/M

#58874 Include more information when multiple security groups are tagged
  pkg/cloudprovider/providers/aws/aws.go
  pkg/cloudprovider/providers/aws/aws_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/S

#62166 fluentd-elasticsearch addon: allow graceful shutdown in fluentd-es image.
  cluster/addons/fluentd-elasticsearch/fluentd-es-image/run.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63566 Automated cherry pick of #63526: adding support for VM name with extra Separator String
  pkg/cloudprovider/providers/azure/azure_vmss_cache.go
  pkg/cloudprovider/providers/azure/azure_vmss_cache_test.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, size/S

#62354 Add support for AWS charm
  cluster/juju/layers/kubernetes-master/layer.yaml
  cluster/juju/layers/kubernetes-master/metadata.yaml
  cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py
  cluster/juju/layers/kubernetes-worker/layer.yaml
  cluster/juju/layers/kubernetes-worker/metadata.yaml
  cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#62934 Refactor GetResourceRequest and GetResourceLimit
  pkg/scheduler/algorithm/predicates/predicates.go
  pkg/scheduler/algorithm/priorities/resource_limits.go
  pkg/scheduler/schedulercache/node_info.go
  pkg/scheduler/schedulercache/node_info_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/scheduling, size/L

#63502 Run resource discovery in parallel
  pkg/kubectl/cmd/util/cached_discovery.go
  staging/src/k8s.io/client-go/discovery/BUILD
  staging/src/k8s.io/client-go/discovery/discovery_client.go
  staging/src/k8s.io/client-go/discovery/discovery_client_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, sig/cli, size/L

#63597 don't block e2e namespace cleanup checks on metrics.k8s.io API group
  test/e2e/framework/util.go
Labels: approved, cncf-cla: yes, lgtm, queue/fix, release-note-none, size/XS

#63599 push ToRESTMapper down a layer
  pkg/kubectl/cmd/testing/fake.go
  pkg/kubectl/cmd/util/config_flags.go
  pkg/kubectl/cmd/util/factory.go
  pkg/kubectl/cmd/util/factory_builder.go
  pkg/kubectl/cmd/util/factory_client_access.go
  pkg/kubectl/cmd/util/factory_object_mapping.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#62850 kubeadm-token: search for existing kubeconfig files
  cmd/kubeadm/app/cmd/BUILD
  cmd/kubeadm/app/cmd/token.go
  cmd/kubeadm/app/cmd/token_test.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note, sig/cluster-lifecycle, size/M

#63504 Improve where we load builds from for kubeadm upgrade jobs
  cmd/kubeadm/app/util/version.go
  cmd/kubeadm/app/util/version_test.go
Labels: approved, area/kubeadm, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/cluster-lifecycle, size/XS, status/approved-for-milestone

#63107 Automated cherry pick of #62669 upstream release 1.10
  build/root/BUILD.root
  cluster/BUILD
  cluster/gce/BUILD
  cluster/gce/gci/BUILD
  cluster/gce/gci/apiserver_manifest_test.go
  cluster/gce/gci/configure-helper.sh
  cluster/gce/gci/configure_helper_test.go
  cluster/gce/manifests/BUILD
  cluster/gce/manifests/kms-plugin-container.manifest
  cluster/gce/manifests/kube-apiserver.manifest
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note-none, size/XL

#59284 Exclude keys containing empty patches in the final patch
  pkg/kubectl/cmd/apply_test.go
  staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
  staging/src/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63602 category expansion can only come from the server
  hack/.golint_failures
  pkg/kubectl/BUILD
  pkg/kubectl/categories/BUILD
  pkg/kubectl/cmd/testing/BUILD
  pkg/kubectl/cmd/testing/fake.go
  pkg/kubectl/cmd/util/BUILD
  pkg/kubectl/cmd/util/factory.go
  pkg/kubectl/cmd/util/factory_builder.go
  pkg/kubectl/cmd/util/factory_object_mapping.go
  pkg/kubectl/cmd/util/factory_test.go
  pkg/kubectl/resource/BUILD
  pkg/kubectl/resource/builder.go
  pkg/kubectl/resource/builder_test.go
  pkg/kubectl/resource/fake.go
  staging/src/k8s.io/client-go/restmapper/BUILD
  staging/src/k8s.io/client-go/restmapper/category_expansion.go
  staging/src/k8s.io/client-go/restmapper/category_expansion_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63593 Fix typo in envelope transform error message
  staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/envelope.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note-none, size/XS

#63539 Refactor cachingSecretManager
  pkg/kubelet/secret/BUILD
  pkg/kubelet/secret/caching_secret_manager.go
  pkg/kubelet/secret/caching_secret_manager_test.go
  pkg/kubelet/secret/secret_manager.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63547 [1.8] Automated cherry pick of #63045: passthrough readOnly to subpath
  pkg/kubelet/kubelet_pods.go
  pkg/util/mount/fake.go
  pkg/util/mount/mount.go
  pkg/util/mount/mount_linux.go
  pkg/util/mount/mount_linux_test.go
  test/e2e/storage/subpath.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note, size/L

#63452 [kubeadm] Support `HostPathType` of ExtraVolumes in the kubeadm configuration file.
  cmd/kubeadm/app/apis/kubeadm/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/types.go
  cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
  cmd/kubeadm/app/phases/controlplane/volumes.go
  cmd/kubeadm/app/phases/controlplane/volumes_test.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/M

#63624 continued discovery cleanup, aggregator e2e test deflaking
  test/e2e/apimachinery/aggregator.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, release-note-none, sig/api-machinery, size/XS

#59847 explicit kubelet config key in Node.Spec.ConfigSource.ConfigMap
  api/openapi-spec/swagger.json
  api/swagger-spec/v1.json
  cmd/kubeadm/app/phases/kubelet/kubelet.go
  cmd/kubeadm/app/phases/kubelet/kubelet_test.go
  docs/api-reference/v1/definitions.html
  pkg/apis/core/register.go
  pkg/apis/core/types.go
  pkg/apis/core/v1/zz_generated.conversion.go
  pkg/apis/core/validation/validation.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/kubelet/apis/kubeletconfig/BUILD
  pkg/kubelet/apis/kubeletconfig/register.go
  pkg/kubelet/apis/kubeletconfig/types.go
  pkg/kubelet/apis/kubeletconfig/v1beta1/BUILD
  pkg/kubelet/apis/kubeletconfig/v1beta1/register.go
  pkg/kubelet/apis/kubeletconfig/v1beta1/types.go
  pkg/kubelet/apis/kubeletconfig/v1beta1/zz_generated.conversion.go
  pkg/kubelet/apis/kubeletconfig/v1beta1/zz_generated.deepcopy.go
  pkg/kubelet/apis/kubeletconfig/zz_generated.deepcopy.go
  pkg/kubelet/kubeletconfig/BUILD
  pkg/kubelet/kubeletconfig/checkpoint/BUILD
  pkg/kubelet/kubeletconfig/checkpoint/download.go
  pkg/kubelet/kubeletconfig/checkpoint/download_test.go
  pkg/kubelet/kubeletconfig/checkpoint/store/fsstore.go
  pkg/kubelet/kubeletconfig/checkpoint/store/fsstore_test.go
  pkg/kubelet/kubeletconfig/checkpoint/store/store_test.go
  pkg/kubelet/kubeletconfig/status/status.go
  pkg/kubelet/kubeletconfig/util/codec/codec.go
  pkg/kubelet/kubeletconfig/util/equal/equal.go
  pkg/kubelet/kubeletconfig/watch.go
  plugin/pkg/admission/noderestriction/admission_test.go
  plugin/pkg/auth/authorizer/node/graph.go
  plugin/pkg/auth/authorizer/node/graph_populator.go
  plugin/pkg/auth/authorizer/node/node_authorizer_test.go
  staging/src/k8s.io/api/core/v1/generated.pb.go
  staging/src/k8s.io/api/core/v1/generated.proto
  staging/src/k8s.io/api/core/v1/register.go
  staging/src/k8s.io/api/core/v1/types.go
  staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go
  staging/src/k8s.io/api/core/v1/zz_generated.deepcopy.go
  test/e2e_node/dynamic_kubelet_config_test.go
  test/e2e_node/util.go
  test/integration/apiserver/print_test.go
  test/integration/auth/node_test.go
  test/integration/etcd/etcd_storage_path_test.go
Labels: approved, area/kubeadm, area/kubelet, area/kubelet-api, cncf-cla: yes, kind/api-change, kind/feature, kind/new-api, lgtm, priority/important-soon, release-note, sig/cluster-lifecycle, sig/node, sig/scheduling, size/XL, status/approved-for-milestone

#61976 Stop() for Ticker to enable leak-free code
  pkg/kubelet/eviction/eviction_manager.go
  staging/src/k8s.io/apimachinery/pkg/util/clock/clock.go
  staging/src/k8s.io/apimachinery/pkg/util/clock/clock_test.go
  staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go
  staging/src/k8s.io/client-go/util/workqueue/rate_limitting_queue_test.go
  test/images/logs-generator/logs_generator.go
Labels: approved, cncf-cla: yes, kind/enhancement, lgtm, release-note-none, sig/api-machinery, size/L

#63442 change deprecated Kubelet --allow-privileged flag default to true
  cmd/kubelet/app/options/options.go
Labels: approved, area/kubelet-api, area/security, cncf-cla: yes, kind/bug, lgtm, release-note, sig/node, size/XS

#63596 Automated cherry pick of #63504: Improve where we load builds from for kubeadm upgrade jobs
  cmd/kubeadm/app/util/version.go
  cmd/kubeadm/app/util/version_test.go
Labels: approved, area/kubeadm, cherrypick-approved, cherrypick-candidate, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, release-note, sig/cluster-lifecycle, size/XS, status/approved-for-milestone

#63626 Manual cherrypick of kube-openapi changes for release-1.9
  Godeps/Godeps.json
  staging/src/k8s.io/api/Godeps/Godeps.json
  staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apimachinery/Godeps/Godeps.json
  staging/src/k8s.io/apiserver/Godeps/Godeps.json
  staging/src/k8s.io/client-go/Godeps/Godeps.json
  staging/src/k8s.io/code-generator/Godeps/Godeps.json
  staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json
  staging/src/k8s.io/metrics/Godeps/Godeps.json
  staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/sample-controller/Godeps/Godeps.json
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note, sig/api-machinery, size/M

#63587 apiextensions: handle CRD conflict errs in integration tests
  staging/src/k8s.io/apiextensions-apiserver/test/integration/subresources_test.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/testserver/resources.go
  staging/src/k8s.io/apiextensions-apiserver/test/integration/validation_test.go
Labels: approved, area/custom-resources, cncf-cla: yes, lgtm, release-note-none, sig/api-machinery, size/L

#63424 Fix #63183 Pods on different nodes mount Ceph RBD PVC stuck on ContainerCreating
  pkg/volume/rbd/rbd.go
  pkg/volume/rbd/rbd_test.go
  pkg/volume/rbd/rbd_util.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63657 Remove 20x factor in garbage-collector qps
  cmd/kube-controller-manager/app/core.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/api-machinery, size/XS

#60200 read openstack auth config from client config
  staging/src/k8s.io/client-go/plugin/pkg/client/auth/openstack/BUILD
  staging/src/k8s.io/client-go/plugin/pkg/client/auth/openstack/openstack.go
  staging/src/k8s.io/client-go/plugin/pkg/client/auth/openstack/openstack_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note, sig/openstack, size/L

#63623 kubeadm-init: add details about --token
  cmd/kubeadm/app/cmd/init.go
Labels: approved, area/kubeadm, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/XS

#63406 Apply pod name and namespace labels for pod cgroup for cadvisor metrics
  pkg/kubelet/cm/BUILD
  pkg/kubelet/cm/pod_container_manager_linux.go
  pkg/kubelet/cm/pod_container_manager_linux_test.go
  pkg/kubelet/cm/pod_container_manager_stub.go
  pkg/kubelet/cm/types.go
  pkg/kubelet/kubelet_getters.go
  pkg/kubelet/server/server.go
  pkg/kubelet/server/server_test.go
  pkg/kubelet/server/stats/handler.go
  pkg/kubelet/server/stats/testing/mock_stats_provider.go
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#63613 construct resource.Builder from kubeconfig flags
  pkg/kubectl/cmd/cmd.go
  pkg/kubectl/cmd/util/BUILD
  pkg/kubectl/cmd/util/config_flags.go
  pkg/kubectl/cmd/util/factory.go
  pkg/kubectl/cmd/util/factory_builder.go
  pkg/kubectl/cmd/util/factory_client_access.go
  pkg/kubectl/cmd/util/factory_object_mapping.go
  pkg/kubectl/cmd/util/kubectl_match_version.go
  pkg/kubectl/resource/BUILD
  pkg/kubectl/resource/builder.go
  pkg/kubectl/resource/interfaces.go
  staging/src/k8s.io/client-go/restmapper/category_expansion.go
  staging/src/k8s.io/client-go/restmapper/category_expansion_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63635 Manual cherrypick of kube-openapi changes for release-1.8
  Godeps/Godeps.json
  staging/src/k8s.io/api/Godeps/Godeps.json
  staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json
  staging/src/k8s.io/apimachinery/Godeps/Godeps.json
  staging/src/k8s.io/apiserver/Godeps/Godeps.json
  staging/src/k8s.io/client-go/Godeps/Godeps.json
  staging/src/k8s.io/code-generator/Godeps/Godeps.json
  staging/src/k8s.io/kube-aggregator/Godeps/Godeps.json
  staging/src/k8s.io/metrics/Godeps/Godeps.json
  staging/src/k8s.io/sample-apiserver/Godeps/Godeps.json
  vendor/k8s.io/kube-openapi/pkg/aggregator/aggregator.go
Labels: approved, cherrypick-approved, cncf-cla: yes, lgtm, release-note, sig/api-machinery, size/M

#61913 Remove ActiveDeadlineSeconds from Watch e2e Test
  test/e2e/apimachinery/watch.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#62665 Kubeadm e2e
  hack/.golint_failures
  hack/make-rules/test.sh
  test/BUILD
  test/e2e_kubeadm/BUILD
  test/e2e_kubeadm/e2e_kubeadm_suite_test.go
  test/e2e_kubeadm/kubeadm_test.go
  test/e2e_kubeadm/matchers.go
  test/e2e_kubeadm/runner/local/BUILD
  test/e2e_kubeadm/runner/local/run_local.go
  test/e2e_kubeadm/tests/BUILD
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/cluster-lifecycle, size/L

#62194 Correct the returned message
  staging/src/k8s.io/apiserver/pkg/endpoints/audit_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63616 Uncordon the node after upgrade
  cluster/gce/upgrade.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#63672 Bump down to cos-stable-65 in config-test
  cluster/gce/config-test.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63450 Adds kubeadm images command
  cmd/kubeadm/app/cmd/BUILD
  cmd/kubeadm/app/cmd/config.go
  cmd/kubeadm/app/cmd/config_test.go
  cmd/kubeadm/app/images/BUILD
  cmd/kubeadm/app/images/images.go
  docs/.generated_docs
  docs/admin/kubeadm_config_list-images.md
  docs/man/man1/kubeadm-config-list-images.1
Labels: approved, area/kubeadm, cncf-cla: yes, kind/old-docs, lgtm, release-note, sig/cluster-lifecycle, size/L

#63511 cleanup TODOs from PrintFlags wiring
  pkg/kubectl/cmd/apply.go
  pkg/kubectl/cmd/create/BUILD
  pkg/kubectl/cmd/create/create.go
  pkg/kubectl/cmd/create/create_clusterrolebinding.go
  pkg/kubectl/cmd/create/create_configmap.go
  pkg/kubectl/cmd/create/create_deployment.go
  pkg/kubectl/cmd/create/create_deployment_test.go
  pkg/kubectl/cmd/create/create_namespace.go
  pkg/kubectl/cmd/create/create_pdb.go
  pkg/kubectl/cmd/create/create_pdb_test.go
  pkg/kubectl/cmd/create/create_priorityclass.go
  pkg/kubectl/cmd/create/create_priorityclass_test.go
  pkg/kubectl/cmd/create/create_quota.go
  pkg/kubectl/cmd/create/create_rolebinding.go
  pkg/kubectl/cmd/create/create_secret.go
  pkg/kubectl/cmd/create/create_service.go
  pkg/kubectl/cmd/create/create_serviceaccount.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63561 remove legacyscheme dep from printFlags
  pkg/kubectl/cmd/annotate.go
  pkg/kubectl/cmd/apply.go
  pkg/kubectl/cmd/apply_set_last_applied.go
  pkg/kubectl/cmd/auth/reconcile.go
  pkg/kubectl/cmd/autoscale.go
  pkg/kubectl/cmd/certificates.go
  pkg/kubectl/cmd/clusterinfo_dump.go
  pkg/kubectl/cmd/config/BUILD
  pkg/kubectl/cmd/config/flags.go
  pkg/kubectl/cmd/config/view.go
  pkg/kubectl/cmd/convert.go
  pkg/kubectl/cmd/create/create.go
  pkg/kubectl/cmd/create/create_deployment_test.go
  pkg/kubectl/cmd/create/create_job.go
  pkg/kubectl/cmd/create/create_job_test.go
  pkg/kubectl/cmd/create/create_pdb_test.go
  pkg/kubectl/cmd/create/create_priorityclass_test.go
  pkg/kubectl/cmd/create/create_role.go
  pkg/kubectl/cmd/create/create_role_test.go
  pkg/kubectl/cmd/create/flags.go
  pkg/kubectl/cmd/drain.go
  pkg/kubectl/cmd/drain_test.go
  pkg/kubectl/cmd/expose.go
  pkg/kubectl/cmd/get/get.go
  pkg/kubectl/cmd/get/get_flags.go
  pkg/kubectl/cmd/label.go
  pkg/kubectl/cmd/patch.go
  pkg/kubectl/cmd/replace.go
  pkg/kubectl/cmd/rollingupdate.go
  pkg/kubectl/cmd/rollout/rollout_pause.go
  pkg/kubectl/cmd/rollout/rollout_resume.go
  pkg/kubectl/cmd/rollout/rollout_undo.go
  pkg/kubectl/cmd/run.go
  pkg/kubectl/cmd/run_test.go
  pkg/kubectl/cmd/scale.go
  pkg/kubectl/cmd/set/set_env.go
  pkg/kubectl/cmd/set/set_env_test.go
  pkg/kubectl/cmd/set/set_image.go
  pkg/kubectl/cmd/set/set_image_test.go
  pkg/kubectl/cmd/set/set_resources.go
  pkg/kubectl/cmd/set/set_resources_test.go
  pkg/kubectl/cmd/set/set_selector.go
  pkg/kubectl/cmd/set/set_serviceaccount.go
  pkg/kubectl/cmd/set/set_serviceaccount_test.go
  pkg/kubectl/cmd/set/set_subject.go
  pkg/kubectl/cmd/taint.go
  pkg/kubectl/cmd/util/editor/BUILD
  pkg/kubectl/cmd/util/editor/editoptions.go
  pkg/printers/flags.go
  pkg/printers/internalversion/printers_test.go
  pkg/printers/json_yaml_flags.go
  pkg/printers/json_yaml_flags_test.go
  pkg/printers/name_flags.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#63289 Cleanup DaemonSet after each integration test.
  test/integration/daemonset/BUILD
  test/integration/daemonset/daemonset_test.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, sig/apps, size/M

#62244 fix "kubectl create --raw"
  pkg/kubectl/cmd/create/create.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63685 GCE: Add Patch method to GA Backend Services
  pkg/cloudprovider/providers/gce/cloud/gen.go
  pkg/cloudprovider/providers/gce/cloud/meta/meta.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#59727 should use time.Since instead of time.Now().Sub
  pkg/cloudprovider/providers/gce/gce_op.go
  pkg/controller/bootstrap/tokencleaner.go
  pkg/controller/certificates/certificate_controller.go
  pkg/controller/daemon/daemon_controller.go
  pkg/controller/disruption/disruption.go
  pkg/controller/endpoint/endpoints_controller.go
  pkg/controller/job/job_controller.go
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/resourcequota/resource_quota_controller.go
  pkg/controller/route/route_controller.go
  pkg/controller/serviceaccount/serviceaccounts_controller.go
  pkg/controller/statefulset/stateful_set.go
  pkg/controller/volume/pvcprotection/pvc_protection_controller.go
  pkg/controller/volume/pvprotection/pv_protection_controller.go
  pkg/kubelet/dockershim/libdocker/kube_docker_client.go
  pkg/printers/internalversion/printers.go
  pkg/proxy/userspace/roundrobin.go
  pkg/proxy/winuserspace/roundrobin.go
  pkg/ssh/ssh.go
  staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go
  staging/src/k8s.io/client-go/plugin/pkg/client/auth/openstack/openstack.go
  test/e2e/framework/util.go
  test/e2e/scalability/density.go
  test/images/liveness/server.go
  test/images/resource-consumer/consume-cpu/consume_cpu.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#63468 fix annotation of APIGroupInfo
  staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#63639 Automated cherry pick of #63385: fix status subresource
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/BUILD
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
  staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy_test.go
Labels: approved, area/custom-resources, cherrypick-approved, cncf-cla: yes, kind/bug, lgtm, sig/api-machinery, size/L

#63246 Add scale-up test from 0 for GPU node-pool
  test/e2e/autoscaling/cluster_size_autoscaling.go
  test/e2e/framework/util.go
  test/utils/runners.go
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
